### ISSUE TITLE
submit form with files and other information

### ISSUE THREAD

**Issue by xmming** [adopted-ember-addons/ember-file-upload#100]
So I have a form that lets user input some product information including images. 
I tried to understand the demo code and it seems that in the demo the you directly call the method file.upload() for the uploading and I did not see model change.

From https://github.com/tim-evans/ember-file-upload/blob/latest/tests/dummy/app/index/route.js

`actions: {
    uploadProof (file) {
      let asset = {
        filename: get(file, 'name'),
        file
      };
      this.currentModel.pushObject(asset);
      return file.upload('/photos/new').then(({ body: { filename, url, type } }) => {
        setProperties(asset, {
          filename,
          preview: url,
          type,
          file: null
        });
      }, function () {});
    }
  }
`
When I read the README on the integration part. The upload call happens before model.save()
  
` try {
      file.readAsDataURL().then(function (url) {
        if (get(photo, 'url') == null) {
          set(photo, 'url', url);
        }
      });

     let response = yield file.upload('/api/images/upload');
      set(photo, 'url', response.headers.Location);
      yield photo.save();
    } catch (e) {
      photo.rollback();
    }`

I tried to do something like this:
`
let product = this.store.createRecord("product", product_details);
product.save();`
product_details is an object with product information and the image of the file.
However, it seems that the product model that created have an empty file. 

Just wondering if this is doable by using model.save() to post information including a file? If yes, what else do I need to do？If not, just wondering if there is a way to do post and file upload at the same time? 

Any help will be appreciated! Thanks!

**Comment by angelomachado** [comment]
That's no possible, I mean not this way. If you want to upload the file by saving the model you need to have a custom adapter. There is an [addon](https://github.com/funtusov/ember-cli-form-data) for that

**Comment by tim-evans** [comment]
This is possible, we do this in our production application- it requires your server endpoint to handle the upload process along with additional data.

You can pass extra data along with the request using the `data` attribute:

```js
import Route from '@ember/routing/route';

export default Route.extend({
  actions: {
    upload(file, { filename, uploadedBy }) {
      return file.upload('/api/photos', {
        data: { filename, uploadedBy }
      }).then((response) => {
        return this.store.push(response);
      });
    }
  }
});
```

**Comment by tim-evans** [comment]
Tracking in https://github.com/tim-evans/ember-file-upload/issues/122

**Comment by gilest** [comment]
Documented as part of public API.

[file.upload() options reference](https://ember-file-upload.pages.dev/api/class/upload-file#upload-options) which includes the `data` option.
