### ISSUE TITLE
The latest published build breaks TypeScript apps

### ISSUE THREAD

**Issue by andreyfel** [adopted-ember-addons/ember-file-upload#1035]
Updating from 8.3.1 to 8.4.0 breaks linting in our app as it starts thinking that `getOwner` returns `any`.
The root cause of this are these comments added to published type declarations:
```
/// <reference types="ember-source/types/stable/@ember/owner/index" />
/// <reference types="ember-source/types/stable/@ember/controller/owner-ext" />
/// <reference types="ember-source/types/stable/@ember/routing/owner-ext" />
/// <reference types="ember-source/types/stable/@ember/service/owner-ext" />
```
https://www.npmjs.com/package/ember-file-upload/v/8.4.0?activeTab=code

Here is the relevant ticket in TypeScript repo:
https://github.com/microsoft/TypeScript/issues/56571

Not sure what the addon authors should do about it. 
- Manually delete those `///` comments before publishing?
- Rollback Typescript to 5.2?
- Wait until ember core team gives a recommendation?

I saw a discussion in Discord in `dev-typescript` channel but it hasn't resolved into any recommendations so far.

**Comment by andreyfel** [comment]
Recommendation from @null
```
If you're building the library, you can either downgrade typescript or use a post-build script to remove the triple slash reference lines before publish.
```

**Comment by NullVoxPopuli** [comment]
Related:
- https://github.com/tracked-tools/ember-async-data/pull/704/files
- https://github.com/tracked-tools/ember-async-data/pull/705#discussion_r1310279164 
- https://github.com/tildeio/ember-element-helper/pull/113
- https://github.com/tildeio/ember-element-helper/issues/111
- https://github.com/jmurphyau/ember-truth-helpers/pull/188


A work around:

```
 "build:types": "glint --declaration && grep -r -l '///' declarations/ | sort | uniq | xargs perl -e \"s/\\/\\/\\/.*$//\" -pi",
```
In package.json

**Comment by gilest** [comment]
Ahh change management in typescript is frustrating.

I was confident in releasing after this upgrade because we run type-checking in CI (for TS 5.0, 5.1, 5.2, 5.3). This issue does not fail those typechecks 😢 

Any ideas how I can add regression coverage for this? Do I need to consume the `Owner` type elsewhere in the tests.

**Comment by gilest** [comment]
Rollback released in `8.4.1`

**Comment by NullVoxPopuli** [comment]
> Any ideas how I can add regression coverage for this?

add type-checking to the scenario testing

> Do I need to import or use the Owner type elsewhere in the tests?

this is what ember-resources does: https://github.com/NullVoxPopuli/ember-resources/blob/f0a8b8506257add362e84dad49af8ec9218c8a66/ember-resources/src/core/function-based/manager.ts#L27-L37

> Do I need to import or use the Owner type elsewhere in the tests?

you could possible cast to any or drop support for ember versions that don't have the Owner type.

**Comment by NullVoxPopuli** [comment]
Made a tool to help out in the future: https://github.com/NullVoxPopuli/fix-bad-declaration-output
