### ISSUE TITLE
`Timer` not exported from DefinitelyTyped `@ember/runloop` package

### ISSUE THREAD

**Issue by charlesfries** [adopted-ember-addons/ember-file-upload#1063]
#961 switched `EmberRunTimer` imported from `@ember/runloop/types` to `Timer` imported from `@ember/runloop`.

https://github.com/adopted-ember-addons/ember-file-upload/blob/487168ecb942efe66174cd2e82d57111fcafaafc/ember-file-upload/src/system/drag-listener.ts#L2

It seems that the DefinitelyTyped `@ember/runloop` package does not export this `Timer` interface.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__runloop/index.d.ts

Resulting in this error:

![image](https://github.com/adopted-ember-addons/ember-file-upload/assets/2275005/fa49d391-9864-4d39-b163-bc556de45bf5)

Unfortunately I am unable to switch to the internal Ember types because EmberData is not yet compatible with those types AFAIK.

My question is:

1. Should this addon be compatible with the older DT types?
2. If so, is this something that should be fixed here or in DT? If it's the latter feel free to close this issue, I will open a new one in DT.

**Comment by jelhan** [comment]
I asked the same question regarding another addon in Ember Discord. Got the recommendation that it should be fixed in DefinetlyTyped.

**Comment by charlesfries** [comment]
Fixed in `@types/ember__runloop@4.0.10`
