### ISSUE TITLE
Can't close file browser in Edge 14

### ISSUE THREAD

**Issue by ewal** [adopted-ember-addons/ember-file-upload#110]
Hello and thank you for a great addon. There's an issue in MS Edge 14 where the file browser can't be closed, or rather re-opens, due to the file input being wrapped in a label. The issue is described here https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/ together with a JS fiddle.

**Comment by tim-evans** [comment]
The ticket says it's fixed. Is this the most recent version of edge?

**Comment by richardjohansson** [comment]
The issue is resolved in the most recent version of Edge. This issue is regarding Edge 14.

**Comment by tim-evans** [comment]
@richardjohansson thanks for the clarification :)

It looks like the usage of this is fairly small. Is there a way this issue can be resolved by communicating with users (by upgrading Edge) instead of a patch here? The code in question is pretty key into how this works properly

**Comment by ewal** [comment]
I believe that moving out the input from the label wont cause any issues since you've specified the for attribute on the label. Still, I see what you mean :)

**Comment by tim-evans** [comment]
I'd be willing to try this, but I'm wary of breaking styles and UI 😭

**Comment by jelhan** [comment]
Is this still effecting an Edge version that is supported by Microsoft?

**Comment by ewal** [comment]
I'm closing this issue. Don't even now what the current version of Edge is and not gonna even bother to look it up.
