### ISSUE TITLE
Is there a way to manipulate file queue?

### ISSUE THREAD

**Issue by NerijusD** [adopted-ember-addons/ember-file-upload#113]
For an example removing specific file from the queue? Or manually add files?

**Comment by tim-evans** [comment]
@NerijusD yes! You can call `push` / `remove` on the file queue.

See https://github.com/tim-evans/ember-file-upload/blob/latest/addon/queue.js#L89
https://github.com/tim-evans/ember-file-upload/blob/latest/addon/queue.js#L50

**Comment by tim-evans** [comment]
Tracking this in https://github.com/tim-evans/ember-file-upload/issues/122

**Comment by jelhan** [comment]
It's documented now: https://adopted-ember-addons.github.io/ember-file-upload/docs/api/modules/ember-file-upload/queue~Queue#push
