### ISSUE TITLE
Multiple {{file-upload}} Components with Different Names throw error.

### ISSUE THREAD

**Issue by Parrryy** [adopted-ember-addons/ember-file-upload#119]
I'm having an issue where on the same template I'd like two file-upload components. 

```
{{#file-upload  name="pin-file"
                accept="*/*"
                multiple=true
                onfileadd=(action "uploadPinFile")}}
  <p><i class="fa fa-upload"></i>Add an Pin.</p>
{{/file-upload}}
```
and
```
{{#file-upload  name="post-attachment"
                         accept= '*/*'
                         multiple=false
                         onfileadd=(action "uploadAttachment")}}
  <i class="fa fa-paperclip"></i>
{{/file-upload}}
```

Ember throws this error. (I'm not the best at debugging ember issues at the moment)

```
Uncaught TypeError: Cannot read property 'commit' of null
    at Environment.commit (c12bf008c38b36f4040b.js?r=vendor-frontend-js:22529)
    at Environment.commit (c12bf008c38b36f4040b.js?r=vendor-frontend-js:32591)
    at InteractiveRenderer._renderRootsTransaction (c12bf008c38b36f4040b.js?r=vendor-frontend-js:34716)
    at InteractiveRenderer._revalidate (c12bf008c38b36f4040b.js?r=vendor-frontend-js:34750)
    at invoke (c12bf008c38b36f4040b.js?r=vendor-frontend-js:24462)
    at Queue.flush (c12bf008c38b36f4040b.js?r=vendor-frontend-js:24382)
    at DeferredActionQueues.flush (c12bf008c38b36f4040b.js?r=vendor-frontend-js:24535)
    at Backburner.end (c12bf008c38b36f4040b.js?r=vendor-frontend-js:24667)
    at Backburner._run (c12bf008c38b36f4040b.js?r=vendor-frontend-js:25017)
    at Backburner._join (c12bf008c38b36f4040b.js?r=vendor-frontend-js:24993)
```

If I encapsulate the file-upload with the dropzone example in the Readme.md then it seems to work as expected.

I'm having an issue or can't seem to workout the event that gets fired so I can upload a file when it is dropped any help would be appreciated.

**Comment by tim-evans** [comment]
That's super frustrating! This should definitely work; could you make a twiddle for this? https://ember-twiddle.com

**Comment by Parrryy** [comment]
@tim-evans What's the process of getting th add-on in the twiddle, I've never used twiddle but would be happy to do so.

**Comment by tim-evans** [comment]
@Parrryy if you add the addon as a dependency in https://ember-twiddle.com/?openFiles=twiddle.json%2C it should be installed :)

**Comment by Parrryy** [comment]
https://ember-twiddle.com/7ea3f183238f6c45528686ba7e36503e?openFiles=twiddle.json%2C Not sure if I've done this correctly.

**Comment by tim-evans** [comment]
I've forked your gist here:
https://ember-twiddle.com/bad434113914bdcdd5f8ab06d666b447?openFiles=templates.application.hbs%2C

It looks like `<p>` are invalid children of `<label>` tags 🙄

**Comment by tim-evans** [comment]
The docs that I pulled this from is [here at MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content). There *may* be some changes that can fix this, specifically because of https://github.com/tim-evans/ember-file-upload/issues/110 which affects Edge 14

**Comment by Parrryy** [comment]
@tim-evans I'm more than happy to have a go at fixing this if it hasn't been done already. I will need a little help though as to what you have in mind to fix. Would it be removing the label tag somehow?

**Comment by LucMorrissette** [comment]
@Parrryy 

Try adding unique "for" attributes to each of your uploaders. 

```
 {{#file-upload
              name="photos"
              for="upload-photo2"
              multiple=true
              onfileadd=(action "uploadProof")
              accept="image/*,video/*,audio/*"
            }}
              <a>select them</a>
            {{/file-upload}}
```

**Comment by jelhan** [comment]
Is this still an issue with latest version? Even on latest master? If so we would need a reproduction. Either on CodeSandbox, a repository pushed to GitHub or a failing test provided as a merge request.

**Comment by jelhan** [comment]
The Twiddle shared by @tim-evans in the last comment does not show the error reported initially. I think this is resolved. Otherwise we need a reproduction.
