### ISSUE TITLE
Use ember-cli-addon-docs for documentation

### ISSUE THREAD

**Issue by tim-evans** [adopted-ember-addons/ember-file-upload#122]
The documentation is currently quite poor for this addon, with all of it in the README, and having a (partially) good website for this. This is something that will require a bit of work; the following tasks need to be done:

- [x] 🚀 Get ember-cli-addon-docs installed
- [ ] 📓 Fill out JSDocs for important areas of ember-file-upload
- [ ] ✅ Update tests to run against the documentation instead of the dummy app
- [ ] 🖊 Write documentation (like in the README)

**Comment by raido** [comment]
@tim-evans Hi, I got something going over here - https://github.com/raido/ember-file-upload/tree/ember-cli-addon-docs

Basically just a default installation done and it boots up.

**Comment by tim-evans** [comment]
Brilliant!

**Comment by tim-evans** [comment]
Hi @samselikoff; we seem to be have some issues with the deploy here. I'm not particularly sure whom to get in touch with, but wanted to bring it to your attention.

Thanks for the utterly brilliant addon. This makes my life maintaining addons considerably easier and more pleasant. ❤️

**Comment by raido** [comment]
It seems ember-cli-mirage 0.4.0+ is the culprit in prod builds. I downgraded mirage to 0.3.4 and it seems to work locally at least. PR -> https://github.com/tim-evans/ember-file-upload/pull/129

**Comment by samselikoff** [comment]
@tim-evans et. al., missed this due to a backlog of gh notifications...

Let me know if running into more issues! Or pop into #ec-addon-docs in Slack

**Comment by samselikoff** [comment]
Looks like you have an addon docs site up and running, sweet! 👊

**Comment by gilest** [comment]
@Alonski I think this can be closed.

**Comment by jelhan** [comment]
I think this one is resolved by the awesome work of @gilest in the last weeks.
