### ISSUE TITLE
Not backward compatible with Ember before modules

### ISSUE THREAD

**Issue by j15e** [adopted-ember-addons/ember-file-upload#123]
The build still list `Ember 2.12` as compatible, but it is not anymore. Ember < 2.16 is not supported because of modules introduced in that release. Not sure why, but the issue occurs only with production build.

https://github.com/tim-evans/ember-file-upload/blob/e78af40a9c1b996bd8e34807f55cb7d0a075de90/addon/file.js#L2-L5

 I think you should update your support matrix to reflect that. I had to downgrade to `2.2.4` to get a compatible version with `Ember 2.15`

**Comment by tim-evans** [comment]
Thanks for the info- is the support matrix the one on emberobserver.com?

If so, I can ask them to update the support matrix ❤️

**Comment by j15e** [comment]
PS for those looking for a better solution than downgrading to `2.2.4` you may look at https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill to polyfill ember modules until you upgrade your app to ember 2.16.

**Comment by jelhan** [comment]
Not supporting Ember 2.12 anymore.
