### ISSUE TITLE
Fastboot

### ISSUE THREAD

**Issue by OleRoel** [adopted-ember-addons/ember-file-upload#131]
When I use the ember-file-upload component in a template under Fastboot with a `dev` build I get the following error message in Chrome:

_loader.js:247 Uncaught Error: Could not find module `ember-file-upload/components/file-upload/component` imported from `images-browser/components/file-upload`_

The build instruction is: `ember build -e dev`

Which creates a vendor.js in the dist directory with the following `define` statement:

```
define('ember-file-upload/components/file-upload/component', ['exports', 'ember-file-upload/components/file-upload/template', 'ember-file-upload/system/uuid'], function (exports, _template, _uuid)
...
```

I'd think the module should be definded with this statement. And there is no other error message before the `Could not find...` error message which might block the loading of the module.

My environment is:

```
DEBUG: -------------------------------
DEBUG: Ember                : 3.0.0
DEBUG: Ember Data           : 3.0.2
DEBUG: Ember Bootstrap      : 1.2.1
DEBUG: Ember Django Adapter : 2.0.0
DEBUG: Ember Simple Auth    : 1.5.1
DEBUG: -------------------------------
```

I currently have no clue what might cause the issue. The Fastboot docs didn't help me: 

https://www.ember-fastboot.com/docs/addon-author-guide

**Comment by jelhan** [comment]
Are you still facing this issue with latest releases of ember-file-upload and ember-cli-fastboot?

**Comment by jelhan** [comment]
We might want to add test coverage for FastBoot.

**Comment by OleRoel** [comment]
Uh, sorry for the late reply! I was on family vacation and had some other issues in the meantime.
Unfortunately I can't say much about the issue, since I moved towards Django-Python and didn't work in the JS area for some time. I'd need to unpack the old project and fear that I won't have time for doing so the next weeks. But a test coverage sounds good to me :-)

**Comment by gilest** [comment]
Stale. Not sure if this is still an issue. Please reopen if it is.
