### ISSUE TITLE
Dropzone with multiple files

### ISSUE THREAD

**Issue by geekygrappler** [adopted-ember-addons/ember-file-upload#151]
Hi,

I've been trying to get this to work for a while. Debugging it I can see that `queue.multiple` is `undefined` on my dropzone. It's not really clear to me how I set `queue.multiple` in my app, and if that is all that's needed?

https://github.com/tim-evans/ember-file-upload/blob/latest/addon/system/data-transfer.js#L66

I've just copied the example dropzone and added a `onDrop` action, but I'm getting `dropzone.valid -> false`. Using chrome.

**Comment by tim-evans** [comment]
You'll need to add it to your `{{file-upload}}` component- it should be in the documentation somewhere.

**Comment by geekygrappler** [comment]
Ahhh I changed the name from `photos` to `documents`, but missed one on the `{{file-upload}}`.
Is it that:
`{{file-upload name="some-queue"}}`?
I.e. that the name property is the name of the queue? I ignored the name property as it's not mentioned in the docs, and just set `multiple` to `true` so I had:
```
  {{#file-dropzone
    class="dropzone"
    data-test-document-upload=true
    ondrop=(perform onDrop)
    name="documents" as |dropzone queue|
  }}
    {{#if dropzone.active}}
      {{#if dropzone.valid}}
        Drop to upload
      {{else}}
        Invalid
      {{/if}}
    {{else if queue.files.length}}
      Uploading {{queue.files.length}} files. ({{queue.progress}}%)
    {{else}}
      <p>
        {{#if dropzone.supported}}
          Drag and drop files onto this area to upload them or
        {{/if}}
        {{#file-upload name="photos"
          for="photos-upload"
          accept="image/*"
          multiple=true
          onfileadd=(perform onFileAddd)
        }}
          <a tabindex=0>Upload Documents</a>
        {{/file-upload}}
      </p>
    {{/if}}
  {{/file-dropzone}}
```
The line in the docs is this: 
`To use the uploader, you must provide a name (for proper queueing and bundling of resources), and an upload URL.` Even though I read this it didn't click at all that the `name` attribute on the component was the name of the queue. 😭 

If I am correct I could send over a PR just adding name to the list of attributes for the `{{file-upload}}` component just to make it clear that the `name` attribute sets the name of the `queue` that will be used? If you think that would be valuable to future users.

**Comment by tim-evans** [comment]
Yeah, that would be great to have some docs on that
