### ISSUE TITLE
Queue destroy results in error

### ISSUE THREAD

**Issue by wuron** [adopted-ember-addons/ember-file-upload#157]
Using `destroy` method on queue object results in error. I'm not sure if this method should ever be used, but since it wasn't marked as private, I tried it :)

The `destroy` method calls `delete` on `fileQueue.queues` but `queues` is an Array and it results in "delete is not a function" error.
https://github.com/tim-evans/ember-file-upload/blob/2.5.0/addon/queue.js#L33

Replacing that line with `get(this, 'fileQueue.queues').removeObject(this);` should do the trick, but the `destroy` method is not even mentioned in the docs, so maybe it wasn't meant to be used at all :)

**Comment by jelhan** [comment]
Every method that is not explicitly documented as public should be considered as private. `destroy` method discussed here is part of the internal `EmberObject` implementation. Definitely not part of our public API.
