### ISSUE TITLE
Outdated documentation concerning test helper

### ISSUE THREAD

**Issue by e-cooper** [adopted-ember-addons/ember-file-upload#17]
It seems there used to be a `test-helper.js` file with an `addFiles` method to help with tests which has been deleted, but the documentation still exists for this functionality. It should probably be removed.

**Comment by tim-evans** [comment]
Yeah, this should be. I'm working on a test helper that integrates with ember-cli-mirage, which will provide an easier way to handle this.

**Comment by tim-evans** [comment]
There's test helpers built into the addon now. I'll document these soon.

**Comment by lukemelia** [comment]
+1 on documentation. It's not clear to me how to simulate progress events.

**Comment by tim-evans** [comment]
https://github.com/tim-evans/ember-file-upload/issues/122

**Comment by gilest** [comment]
@Alonski I think this can be closed.
