### ISSUE TITLE
file type validation for dropzones and file filtering for browser incompatible

### ISSUE THREAD

**Issue by LilyLauben** [adopted-ember-addons/ember-file-upload#170]
Hello,

We are using this file uploader to allow users to upload a specific set of image files: .png, .jpg/jpeg, .svg, and .dxf. In our app we have both a dropzone and an 'Upload File' button. We would like to use file validation on the dropzone, and also have the file upload browser filter out all non-matching file types when the user clicks the upload button.

This code works:
```node
          <div class='ui sixteen wide centered column'>
            {{#file-dropzone name='floorplan' as |dropzone queue|}}
                <div class='ui basic segment'>
                  <div class='ui header'>
                    <div class='content'>Upload Floorplan</div>
                  </div>
                </div>
                  <div class='ui center aligned basic segment'>
                    {{#if dropzone.supported}}
                      {{#if dropzone.active}}
                        {{#if dropzone.valid}}
                          <div class='ui tertiary very padded segment'>
                            Drop to here to upload!
                          </div>
                        {{else}}
                          <div class='ui tertiary inverted red very padded segment'>
                            Your file is not a valid format!
                          </div>
                        {{/if}}
                      {{else}}
                        <div class='ui secondary very padded segment'>
                          Drag and drop a JPG, PNG, SVG or DXF onto this area to upload...
                        </div>
                      {{/if}}
                    {{/if}}
                    <div class='ui horizontal divider'>
                      Or
                    </div>
                    <div class='ui segment'>
                      {{#file-upload name='floorplan'
                                    accept='image/jpeg,image/png'
                                    onfileadd=(action 'readAsDataUrl')}}
                        <a id='upload-image' class='ui primary labeled icon button'>
                          Upload Floorplan
                          <i class='upload icon'></i>
                        </a>
                      {{/file-upload}}
                    </div>
                  </div>
            {{/file-dropzone}}
```

However, when we change the `accept` variable like so:
```node
accept='image/jpeg,image/png,image/svg+xml'
```
...the svg is not recognized as a valid file type as the dropzone. This behavior persists even in `image/svg+xml` is the only item present in the string. However, they will become recognized as valid by the dropzone in the following code:
```node
accept= ['image/jpeg','image/png','image/svg+xml']
```
...but with this code, the file filtering on the file browser, which worked with all code up until this point, no longer works at all. It appears to cease working with any type of array input for accept. 

This behavior is exactly the same with our DXF files as well.

**Comment by jelhan** [comment]
Did you resolved the issue? If not a reproduction on latest master would be great. Otherwise please close.

> However, they will become recognized as valid by the dropzone in the following code:
>
> ```
> accept= ['image/jpeg','image/png','image/svg+xml']
> ```

Can not follow here. This doesn't look like a valid Ember template syntax.

**Comment by JonnoFTW** [comment]
@jelhan he's referring to this line here:
https://github.com/adopted-ember-addons/ember-file-upload/blob/master/addon/system/data-transfer.js#L79

I'm also having this issue, some uncommon mimetypes are not detected (eg. json lines) and having a fallback to file extension would help. But drag and drop doesn't always provide the filename and extension (at least not for me in chrome, but it does in firefox).

Ideally, to fix the above issue, all a user should need to do is set:

```hbs
@accept="image/svg+xml,.xml"
```

But this won't work in cases where the filename is not given to the browser.

**Comment by jelhan** [comment]
Let me try to summarize to see if I got the issue correct. Please have in mind that I'm not that familiar with the code base of this addon myself.

The addon checks the type of a given file against a list of accepted file types. The list of accepted file types is passed as `@accept` argument to `<FileUpload>` component. It's a comma separated list of values. It can include extensions such as `.png` or mime types such as `image/png`. This is implemented with this code: https://github.com/adopted-ember-addons/ember-file-upload/blob/120e51ee2ce139b959d91235cf46aab38d2cee39/addon/system/data-transfer.js#L74-L107

This logic has a bug, which affects the mime type `image/svg+xml` but not other. Given a component invocation like this `<FileUpload @accept="image/svg+xml" />`, it should allow the user to upload a SVG file with the extension `.svg`. The browser allows the user to select such a file but it's not uploaded.

Is that correct so far? If so having a reproduction either as an Ember Twiddle or even better as a pull request adding a failing test would be the necessary next step.

**Comment by jelhan** [comment]
> I'm also having this issue, some uncommon mimetypes are not detected (eg. json lines) and having a fallback to file extension would help. But drag and drop doesn't always provide the filename and extension (at least not for me in chrome, but it does in firefox).

This limitation is discussed here: #127
