### ISSUE TITLE
{{queue.progress }} remains "0", while uploading a file after a form is submitted

### ISSUE THREAD

**Issue by rinoldsimon** [adopted-ember-addons/ember-file-upload#171]
hbs:
```
<form submit={{action 'submit'}}>
    {{#file-upload name="avatar"
                   accept="image/*"
                   onfileadd=(action 'setAvatar')}}

        {{#with (file-queue name="avatar") as |queue|}}
          {{queue.progress}}%
        {{/with}}

         {{get (file-queue named="avatar") 'progress'}}%

        <a id="upload-avatar">Add a photo of yourself</a>
    {{/file-upload}}
    <button type="submit"> Upload Image </button>
</form>
```
js:
```
import Controller from '@ember/controller';

export default Controller.extend({
  actions: {
    submit() {
        let file = this.get('avatarFile');
        file.upload('/upload').then((response) => {
         ...
        });
    },

    setAvatar(file) {
      this.set('avatarFile', file);
      file.readAsDataURL().then((url) => {
        ...
      });
    }
  }
});
```

I have used `file-queue` helper as mentioned [here](http://tim-evans.github.io/ember-file-upload/latest/docs/api/helpers/file-queue) to get the progress. Still it remains at `0`. But the image gets uploaded to the browser.

Tried using `{{get (file-queue named="avatar") 'progress'}}%` helper and still the progress remains `0`

**Comment by cwhittl** [comment]
Did you ever get it figured out?

**Comment by rinoldsimon** [comment]
@cwhittl No

**Comment by cwhittl** [comment]
@rinoldsimon here is how I got it to work, it's different from the original example but maybe will help https://gist.github.com/cwhittl/487d57c43f30bcfea2de0af3ff684e1a

**Comment by palyvodaBoi** [comment]
I don't have such property as queue.progress (queue.files.progress or queue.files[0].progress) at all. So question with progress bar is still not resolved for me :(

**Comment by palyvodaBoi** [comment]
Well, i can see event.loaded property in my 'onfileadd' action, but it equals to 0 whole time.

**Comment by aalasolutions** [comment]
any one solved this so far?

**Comment by palyvodaBoi** [comment]
unfortunately no :(
so i didn't show progress

**Comment by Alonski** [comment]
I am open to merging in a PR if someone has the time to tackle this.

**Comment by linearza** [comment]
Ive run into this before, and just did again, it seems the issue is related to the z-indexes of the elements, depending on your layout make sure the `file-upload` component has the highest z-index

**Comment by jelhan** [comment]
A reproduction as an Ember Twiddle or CodeSandbox would be helpful.

**Comment by Alonski** [comment]
@linearza Can you please create a repro?

**Comment by jelhan** [comment]
Closing as stale.
