### ISSUE TITLE
Enable support for file-dropzone without file-upload

### ISSUE THREAD

**Issue by fran-worley** [adopted-ember-addons/ember-file-upload#174]
I have raised a [full issue](https://github.com/kaliber5/ember-bootstrap/issues/672) in the EmberBootstrap repository as I'm pretty sure that is the root cause of the issue, however I thought I would raise it for anyone else who uses both addons and incase you guys can shed some light on how the dropzone and file upload components work that could help me resolve the issue.

**Comment by fran-worley** [comment]
Is there anyway to explicitly link the dropzone to the file-upload component? I wondered if a workaround would be to create the queue in the component js with the onFileAdd, name, multiple == true settings and then pass that into the dropzone and file upload components?

**Comment by fran-worley** [comment]
@tim-evans I have got this working by extending the drop-zone component to accept the same queue options as file-upload:

```
import FileDropzone from 'ember-file-upload/components/file-dropzone/component';
import { get, setProperties, getProperties } from '@ember/object';

export default FileDropzone.extend({
  /**
    A list of MIME types / extensions to be accepted by the input
    @argument accept
    @type {string}
   */
  accept: null,
  
  
  /**
    Whether multiple files can be selected when uploading.
    @argument multiple
    @type {boolean}
   */
  multiple: null,
  
  /**
    `onfileadd` is called when a file is selected.
    When multiple files are selected, this function
    is called once for every file that was selected.
    @argument onfileadd
    @type {function}
    @required
   */
  onfileadd: null,
  
  /**
    If set, disables input and prevents files from being added to the queue
    @argument disabled
    @type {boolean}
    @default false
   */
  disabled: false,

  didReceiveAttrs() {
    this._super(...arguments);
    if (get(this, 'queue')) {
      setProperties(get(this, 'queue'), getProperties(this, 'accept', 'multiple', 'disabled', 'onfileadd'));
    }
  },
});
```

This enables the drop-zone to work without the file-upload component. I was going to raise a PR to enable this and extract the common queue code from the two components but thought I'd check if this was something you'd consider merging first.

**Comment by tim-evans** [comment]
There is a way to link them! Add `name` to the `file-dropzone` and it'll look up the queue 😄

**Comment by fran-worley** [comment]
@tim-evans I get that the point of this issue is that it requires the file-upload component to be rendered for the dropzone to work.

In my example, the drop down component lazy renders so the file upload component doesn’t exist unless it is opened and therefore the queue isn’t setup. I’ve had to extend the drop zone to allow queue settings to be added (as above) which made me wonder why the drop zone doesn’t support these settings as this enables it to work without a file-upload component

**Comment by tim-evans** [comment]
Gotcha! I designed it so it required one to improve accessibility for users; I vaguely remember there being some informational info in accessibility docs around having both, but I don't really recall too much now. I'm happy to accept a PR! ❤️ 

(I'm trying to encourage more accessible UIs through making the accessible approach the easiest approach)
