### ISSUE TITLE
Test helper `upload` not working

### ISSUE THREAD

**Issue by npendery** [adopted-ember-addons/ember-file-upload#175]
Versions:
```json
"ember-cli": "~3.0.0",
"ember-mocha": "^0.13.1",
"ember-file-upload": "^2.5.1",
```

Getting an issue with calling `await upload` in my test. The error returned is: `Error: Must setup rendering context before attempting to interact with elements.`

**Comment by jelhan** [comment]
Please make sure that you have included `setupApplicationTest(hooks)` if it's an acceptance test or `setupRenderingTest(hooks)` if it's an integration test. If you are still facing this issue a reproduction would be helpful.
