### ISSUE TITLE
Chrome tab crashing when uploading video files

### ISSUE THREAD

**Issue by rodrigoyoshida** [adopted-ember-addons/ember-file-upload#179]
The addon makes the Chrome tab crash when trying to upload video files. Tried to upload a 50mb video, both on my app and the sample app the memory footprint goes above 1gb and crashes after a few seconds. Also noticed that it embeds a video tag in the DOM, which might be causing the high memory usage. It does not crash when trying to upload small videos.

I am using Ubuntu Linux 18.04 with Chrome 69 but also tested and confirmed that the same happens on a Windows machine.

**Comment by tim-evans** [comment]
This addon doesn't embed an images or videos; this may be an issue when trying to read the file data from the uploaded file.

**Comment by rodrigoyoshida** [comment]
I recorded the exact time when it appears embedded on the demo page. Tried to upload two videos, my whole computer crashed. I am using an 7th generation Core i5 processor with 8gb ram and SSD. 

![peek 2018-10-08 17-35](https://user-images.githubusercontent.com/3301597/46632488-35b1bc80-cb21-11e8-8ddd-0d862033842b.gif)

**Comment by tim-evans** [comment]
Oh, yeah, that'll break with the demo site, since it's loading the whole video in memory.

**Comment by rodrigoyoshida** [comment]
Is there a way to avoid that?

**Comment by tim-evans** [comment]
On the demo site, no.

**Comment by rodrigoyoshida** [comment]
No, I am basically using the first recipe available on the doc. I'm not sure if the same happens with images.

**Comment by tim-evans** [comment]
Ok! Are you using the code here: http://tim-evans.github.io/ember-file-upload/latest/docs/integration

**Comment by tim-evans** [comment]
Ok; then removing `file.readAsDataURL()` would fix your issue 😄

**Comment by rodrigoyoshida** [comment]
> Ok; then removing `file.readAsDataURL()` would fix your issue

Thanks! It fixed my issue. I did not know the browser actually embeds the media in the DOM to create a URL, that caused me a lot of performance issues.
