### ISSUE TITLE
❤️ New Ownership requested

### ISSUE THREAD

**Issue by tim-evans** [adopted-ember-addons/ember-file-upload#190]
It's time! I believe I'm going to do this for all my addons, but it's definitely time to set them free. I don't really have much of a vision of going forward on this, and am mostly maintaining. I think this makes the most sense to be owned by the larger ember community (because of its generality), but I don't think that really exists.

Anyhoo, thanks for everyone who's contributed- y'all are great!

**Comment by Alonski** [comment]
My company uses this addon in production. I'm willing to take it over and keep it maintained and updated. Thanks for all the hard work! Let's chat on Discord. I'm @Alon on there.

**Comment by Alonski** [comment]
@tim-evans I am still up for taking over control of this :)

**Comment by tim-evans** [comment]
Hi, yes, I was waiting for @melsumner to respond to my cross post here https://discuss.emberjs.com/t/new-maintainers-owners-requested/15768/3

**Comment by Alonski** [comment]
@tim-evans sounds good. You want to move the repo to the adopted ember addons repo. And then I would apply there?

**Comment by tim-evans** [comment]
@Alonski I think that may be best ❤️, since I don't want to have an ad-hoc process for each of my addons.

**Comment by Alonski** [comment]
Ok sounds great. Good luck and thanks for everything @tim-evans !

**Comment by MelSumner** [comment]
@Alonski I've invited you to the org :+1:

**Comment by Alonski** [comment]
@MelSumner so can I just start "owning" this repo/library? Do we have an org on NPM as well that we have publish rights to?

**Comment by donaldwasserman** [comment]
@tim-evans Thanks for everything! This is a great addon and your work is really appreciated!
