### ISSUE TITLE
'aborted' uploads can not be uploaded again

### ISSUE THREAD

**Issue by toovy** [adopted-ember-addons/ember-file-upload#197]
An upload can be aborted by the client like described in https://github.com/tim-evans/ember-file-upload/issues/59.

Currently it is not possible to upload a file again if the client aborted it via uploadPromise.cancel().

Simply adding `aborted` to the array in L54 solves the issue, the file can be uploaded again if the user decides to do so:

https://github.com/tim-evans/ember-file-upload/blob/5a1becfd9363a2d16a09c8b6fe468d64741e7881/addon/file.js#L54

Is there any technical background why this should not be possible? I could create a PR.

**Comment by jelhan** [comment]
Should be fixed by #200.
