### ISSUE TITLE
Remove Observer Usages

### ISSUE THREAD

**Issue by Alonski** [adopted-ember-addons/ember-file-upload#238]
Currently, there are two usages of `observers` in this addon:
1. https://github.com/adopted-ember-addons/ember-file-upload/blob/latest/addon/services/file-queue.js#L78
2. https://github.com/adopted-ember-addons/ember-file-upload/blob/e63a1a9ab05fb34001c1207316f94511556e3fca/addon/queue.js#L158

These files seem oddly similar as well. Maybe we don't need both?

Need to remove these observer usages as observers are less recommended to be used.

**Comment by gilest** [comment]
Removed in #307
