### ISSUE TITLE
Add data to the data field

### ISSUE THREAD

**Issue by bsylvain** [adopted-ember-addons/ember-file-upload#250]
I am trying to use the data field when sending a file :
 ```js
      let response = file.upload('/marketadmin_api/v1/attached_files',
        {fileKey: 'data[attributes][content]',
        data: JSON.parse(`{"data":{"attributes": {"attached-file-type": "${relationName}"}}}`),
        headers:  {Authorization: `Token token="${token}", email="${email}"`}
      })
```
I also tried : `data: {data: {attributes: {"attached-file-type": relationName}}}`
Both sent
```
-----------------------------160731283515537
Content-Disposition: form-data; name="data"
[object Object]
```

How can I send data not interpreted as [object Object] ?

The file itself is correctly sent

**Comment by jelhan** [comment]
The `data` option must a POJO having only strings as values: https://adopted-ember-addons.github.io/ember-file-upload/docs/api/modules/ember-file-upload/file~File#upload

It's passed to `FormData.append()`, which converts the value to strings if it's not a string or a `Blob`: https://github.com/adopted-ember-addons/ember-file-upload/blob/4212ae3a47744c5e32af7032c7755a9ce8b03464/addon/file.js#L297-L303

Do you like to improve the documentation about that one?

**Comment by jelhan** [comment]
Closing as stale.
