### ISSUE TITLE
API works when called by JQuery, but not works with file.upload method

### ISSUE THREAD

**Issue by santanapaulo** [adopted-ember-addons/ember-file-upload#255]
I am not sure why this is happening. I call my API sending files with JQuery and everything works fine, but when I try to send through file-upload (via file.upload method) API does not recognize and fail. The headers I am sending are the same, and I just think it's a problem attaching the file to the request.

The error something related to: javax.mail.MessagingException: Missing start boundary (java.io.IOException).

**Comment by jelhan** [comment]
Did you compared the two requests in network tab? Is there any difference in request headers?

**Comment by jelhan** [comment]
Closing due to missing feedback.
