### ISSUE TITLE
Using angle brackets breaks dropzone drag & drop

### ISSUE THREAD

**Issue by alanlalonde** [adopted-ember-addons/ember-file-upload#260]
Angle bracket invocation does not behave in the same way as regular handlebars invocation.
`
<FileDropzone @name="files">
      <FileUpload @name="files"
                  @accept="*"
                  @multiple={{true}}
                  @onfileadd={{action "upload"}} >
        <a tabindex=0>Add an Image.</a>
      </FileUpload>
</FileDropzone>
`

Dragging and dropping files onto the dropzone doesn't call the @onfileadd action (in this case upload). Using the anchor text to select files does work, however. If code is changed to handlebars, dropping a file on the dropzone calls the appropriate action. 

ember-cli version ~3.10.1

**Comment by Alonski** [comment]
@alanlalonde Can you please create a repository showcasing this issue to help me understand it?

**Comment by gilest** [comment]
@alanlalonde  I think the `@onfileadd` callback will only be called by selecting files by clicking on the `<FileUpload>`.

I think this behaviour is the same regardless of component invocation.

Try adding an `@ondrop` callback to `<FileDropzone>` as well.

You could even have both callbacks call the same action.

For example:

```hbs
<FileDropzone @name="files" @ondrop={{action this.upload}}>
  <FileUpload @name="files" @accept="*" @multiple={{true}} @onfileadd={{action this.upload}}>
    <a tabindex=0>Add an Image.</a>
  </FileUpload>
</FileDropzone>
```

**Comment by jelhan** [comment]
Closed due to missing reproduction. Please feel free to reopen if you still face this issue.

**Comment by camnicklaus** [comment]
I'm having this same issue.. don't have time atm to create an example repo but I just recreated by copying the example code from the docs for the dropzone component. works with curly brace but throws this error with angle brackets:

`Uncaught TypeError: Cannot read property '_addFiles' of undefined`
stack trace refers to this line:
https://github.com/adopted-ember-addons/ember-file-upload/blob/4469a3e36f64167940bac65978b57d1bbd936d1c/addon/components/file-dropzone/component.js#L324

**Comment by gilest** [comment]
@camnicklaus could you please share.

- Examples of the curly and angle-bracket templates
- Version of `ember-source`

**Comment by camnicklaus** [comment]
sure thing!
`ember-source` : 3.17.3
angle-bracket:
```
<FileDropzone
  name="uploads"
  cursor="copy"

  as |dropzone queue|
>
  {{#if dropzone.active}}
    {{#if dropzone.valid}}
      Drop to upload
    {{else}}
      Invalid file
    {{/if}}
  {{else if queue.files.length}}
    Uploading {{queue.files.length}} files. ({{queue.progress}}%)
  {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if dropzone.supported}}
        Drop your logo here or
      {{/if}}
      <FileUpload name="uploads"
        accept="image/*"
        multiple={{true}}
        onfileadd={{this.uploadImage}}
      >
        <a id="upload-image" tabindex=0>select</a>
      </FileUpload>
        a file from your computer
    </p>
  {{/if}}
  </FileDropzone>
```

curly brace:
```
{{#file-dropzone
  name="uploads"
  cursor="copy"

  as |dropzone queue|
}}
  {{#if dropzone.active}}
    {{#if dropzone.valid}}
      Drop to upload
    {{else}}
      Invalid file
    {{/if}}
  {{else if queue.files.length}}
    Uploading {{queue.files.length}} files. ({{queue.progress}}%)
  {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if dropzone.supported}}
        Drop your logo here or
      {{/if}}
      <FileUpload name="uploads"
        accept="image/*"
        multiple={{true}}
        onfileadd={{this.uploadImage}}
      >
        <a id="upload-image" tabindex=0>select</a>
      </FileUpload>
        a file from your computer
    </p>
  {{/if}}
{{/file-dropzone}}
```

**Comment by jelhan** [comment]
You are missing the `@` on invocation and therefore passing `name` and `cursor` as HTML attributes and not as named arguments.

**Comment by camnicklaus** [comment]
oh...
my...
gawwd....
😬 

sorry to take up your time.. and thanks for responding anyway! ❤️

**Comment by gilest** [comment]
> sorry to take up your time.. and thanks for responding anyway! ❤️

Thanks for contributing ❤️
