### ISSUE TITLE
Cannot change HTML method used

### ISSUE THREAD

**Issue by bsylvain** [adopted-ember-addons/ember-file-upload#263]
I want to upload with "PUT" instead of "POST"

I use the following upload : 
```
let response = yield file.upload(
      `${pluralize(modelClass)}/${model.get('id')}`,{
        fileKey: `data[attributes][${attributeName}]`,
        headers:  {Authorization: `Token token="${token}", email="${email}"`,
        method: 'PATCH'}
      })
```

I can see the POST with the correct payload, but It is a POST instead of a PATCH.

**Comment by Alonski** [comment]
@bsylvain Could you please create a repository with a recreation of this issue so that I can check it out?

**Comment by bsylvain** [comment]
Ok, I just found it while reproducing it in twiddle, the method is in the header object. Sorry for the noise.
