### ISSUE TITLE
uploadBinary not working

### ISSUE THREAD

**Issue by nag9329** [adopted-ember-addons/ember-file-upload#264]
Hi,

I'm trying to upload a .tgz file and I thought uploadBinary is the right method to use here. Below is the piece of code I'm trying.

   
    uploadForm: function(file) {
	    $('#progressHudMessage').html('Uploading...');
  	    $('#progressHudOverlay').show();
	   get(this, 'uploadFile').perform(file);
      }
     
    uploadFile: task(function * (file) {
	var _this = this;
	let form = this.store.createRecord('componentDeviceForm', {
		parentBusinessEntityId: _this.get('session.selectedBusinessEntity').get('id'),
		parentBusinessEntity: _this.get('session.selectedBusinessEntity'),
		description:"",
		deviceType:0,
		name:file.name
	});
	let apiPath = this.get('apiPath');
	let accessToken = 'Token token="'+this.get('session.sessionObject.accessToken')+'"';
	form.save().then(function(formData) {
			let uploadUrl = 'https//testUploadurl/attachments.tgz';
			let headers = {
				'Authorization': accessToken
			};
			var settings = {'headers':headers};
			return file.uploadBinary(uploadUrl, settings).then(function(response) {
				$('#progressHudOverlay').hide();
			});
		});
     }).maxConcurrency(3).enqueue()

As soon as I upload a file, I'm getting the following error
POST https//testUploadurl/attachments.tgz net::ERR_ACCESS_DENIED
`
{
     body: ""
    headers: {}
    status: 0
   __proto__: Object
}
`

Please help me in understanding the right type to use. I want the file to upload to the server.

**Comment by Alonski** [comment]
@nag9329 Could you please create a repository recreating the issue to help me understand?
