### ISSUE TITLE
How to have the whole page be a dropzone?

### ISSUE THREAD

**Issue by LuisAverhoff** [adopted-ember-addons/ember-file-upload#266]
I'm having trouble implementing dropzone support for the whole document when the user goes to a specific page. Of course I still want to display a button somewhere in the page in case dropzone support is not available. My approach was the following:

1. Create a component that uses the `filedropzone`(no `fileupload` because then the entire page will be clickable) component and place it as a top level container in the page that I'm in.
2. Use `dropzone.active` and `dropzone.valid` to conditionally render my dropzone on the entire window.
3. Use the `ondrop` event to fetch files that were dropped in the dropzone and add them to the queue.
4. Since this component has no `fileupload` component I needed to give it a name that matches the name of a `fileupload` component that exists somewhere in the page so that they would both have the same `queue`.

This approach doesn't work because there is no `fileupload` component attached to the `filedropzone `component and thus no files will ever be dropped as there is no input attach to it.

You have any ideas how I can accomplish this with this addon?

**Comment by Alonski** [comment]
I am pretty sure that a `fileupload` component must be on the page.
If you don't want to show it you can render it off page maybe?

**Comment by jelhan** [comment]
> I am pretty sure that a `fileupload` component must be on the page.

I'm not sure if we still have that requirement. I thought it was dropped by #276? Of course not released yet.

**Comment by gilest** [comment]
FileUpload no longer needs to be present. This should work fine now.
