### ISSUE TITLE
Docs in readme and on GitHub pages are out of sync

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#273]
The docs in README and GitHub pages are out of sync. At least for the cases I noticed the README is more up-to-date. I don't think it's a good idea to duplicate the docs. I would recommend to reduce the README to a simple usage example and update the docs on GitHug pages.

**Comment by Alonski** [comment]
Awesome catch @jelhan . Can you please point to the exact issues? Also a PR would be very welcome

**Comment by jelhan** [comment]
Fixed by #281
