### ISSUE TITLE
Add liniting rule to enforce LF line endings

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#279]
Currently line endings are only checked for JavaScript (ESLint) and Template (TemplateLint) files. They should be checked on other files also to prevent a regression of #278.

**Comment by Alonski** [comment]
I recommend integrating Prettier and then using Prettier to enforce this. Can't believe I haven't done that yet 😅 
I find it hard to work in codebases that don't use Prettier 😄

**Comment by gilest** [comment]
All repos now use `prettier/recommended`. I think this is resolved.
