### ISSUE TITLE
Rename development branch from latest to master

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#280]
I would suggest to rename the default branch from latest to master. This seems to be the de facto standard in ember ecosystem. IMO it's confusing to have another name. I can't count how many times I tried a `git checkout master` or `git rebase master`.

**Comment by gilest** [comment]
This would be OK with me, but I'm not sure what effects it might have on builds, docs, automation etc.

**Comment by gilest** [comment]
Just noticed that the 'Edit this page' links on the addon docs site expect a `master` branch to exist.

They are all 404 at the moment.

Link example:
https://github.com/adopted-ember-addons/ember-file-upload/edit/master/tests/dummy/app/templates/docs/index.md

[Addon docs site page](https://adopted-ember-addons.github.io/ember-file-upload/docs/)
