### ISSUE TITLE
Rename events to camelCase

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#284]
Events are currently written in lowercase: `onfileadd`, `ondrop`, `ondragenter`, `ondragleave`.

As far as I'm aware camelCase event names gets more and more a shared convention in ember ecosystem. Even Ember Power Select switched it's API in the latest major release to camelCase event names.

I think we should do the same and rename to: `onFileAdd`, `onDrop`, `onDragEnter`, `onDragLeave`.

If we don't want to introduce a breaking change, it could be done with [`deprecatingAlias`](https://api.emberjs.com/ember/3.13/functions/@ember%2Fobject%2Fcomputed/deprecatingAlias).

**Comment by gilest** [comment]
Closed by #328
