### ISSUE TITLE
Cannot use <a> element inside of file-upload component on Internet Explorer

### ISSUE THREAD

**Issue by Caltor** [adopted-ember-addons/ember-file-upload#298]
I'm creating a new issue for this as per https://github.com/adopted-ember-addons/ember-file-upload/issues/16#issuecomment-321140472

If you use an <a> element inside of `{{file-upload}}` on Internet Explorer then when you click the component nothing happens. Nada! As the docs show using <a> elements this causes any IE users/developers to conclude that the add-on doesn't work.

**Comment by jelhan** [comment]
Considering to drop IE11 support for next major version. Seems like it's causing a lot of maintenance costs but no one is willing to do the work. Please speak up in #306 if you need IE11 support and are willing to help support it.
