### ISSUE TITLE
Drag and drop not working in IE 11

### ISSUE THREAD

**Issue by Caltor** [adopted-ember-addons/ember-file-upload#299]
This isn't working for me with version 2.7.1 of ember-file-upload. This works fine in Chrome and Firefox but in IE 11 when you drag files over the dropzone the message changes to "Drop to upload" and just sticks there but nothing actually happens. I have ensured that IE 11 is a target in config/targets.js and that polyfill is enabled in the ember-cli-build.js as follows.

Here is a MCVE. Well it's almost C(omplete), you will have to write your own backend service or mock something to handle the file upload. 😁 
```
'ember-cli-babel': {
    includePolyfill: true
},

```
**template.hbs**
```
<div class="alert alert-info">
    {{#file-dropzone name="photos" as |dropzone queue|}}
        {{#if dropzone.active}}
            {{#if dropzone.valid}}
                Drop to upload
            {{else}}
                Invalid
            {{/if}}
        {{else if queue.files.length}}
            Uploading {{queue.files.length}} files. ({{queue.progress}}%)
        {{else}}
            <h4>Upload Images</h4>
            <p>
                {{#if dropzone.supported}}
                    Drag and drop images onto this area to upload them or
                {{/if}}
                {{#file-upload name="photos"
                     multiple=true
                     onfileadd=(action "uploadImage")}}
                    <span id="upload-image" tabindex="0" class="span-link">Add an Image.</span>
                {{/file-upload}}
            </p>
        {{/if}}
    {{/file-dropzone}}
</div>
```

**controller.js**
```
import Controller from '@ember/controller';

export default Controller.extend({
    actions: {
        uploadImage(file) {
            console.log("uploadImage fired!");
            console.log("file: ", file);
            file.upload("http://localhost:4201/api/document-store").then(x => {
                console.log("x: ", x);
            }, y => {
                console.error("y: ", y);
            });
        }
    }
});
```

There seems to have been a similar problem with this pre v2.4.4 but it was slightly different to what I am experiencing and according to [this comment](https://github.com/adopted-ember-addons/ember-file-upload/issues/141#issuecomment-383587095_) it was resolved. So either it's not working again or something else has happened. Or the very real possibility that I'm doing something wrong!

**Comment by Alonski** [comment]
Thanks for the bug report @Caltor !
Do you by chance have the bandwidth to create a fix for this?

**Comment by Caltor** [comment]
Wish I did mate, sorry! We're behind on our project and my manager is cracking the whip. I've coded round it for now as follows

{{#if (user-agent "browser.isIE")}}
    {{!-- Drag and drop doesn't work in IE - use sigle file selection --}}
    {{#file-upload name="uploads"
        multiple=true
        onfileadd=(action "uploadFile")}}
        {{!-- This needs to be a span rather than an a(nchor) tag otherwise it won't work in IE --}}
        <span id="uploadfile" class="span-link" tabindex="0">Add a file</span>
    {{/file-upload}}
{{else}}
   // usual file upload stuff including drag and drop
{{/if}}

**Comment by jelhan** [comment]
Considering to drop IE11 support for next major version. Seems like it's causing a lot of maintenance costs but no one is willing to do the work. Please speak up in #306 if you need IE11 support and are willing to help support it.
