### ISSUE TITLE
Unexpected Token errors when copying your code from the README...?

### ISSUE THREAD

**Issue by jfrux** [adopted-ember-addons/ember-file-upload#30]
Is this even valid? or am I missing something?

**Comment by tim-evans** [comment]
Probably invalid

**Comment by tim-evans** [comment]
Oops! 🤷‍♂️

**Comment by joshuairl** [comment]
Phew, thought I was losing my mind for a minute... hahaha... something with the try catch.

**Comment by gilest** [comment]
@Alonski I think this can be closed.
