### ISSUE TITLE
Firefox Dragging in and dragging out of many files on the dropzone causes browser freeze

### ISSUE THREAD

**Issue by fortuneless** [adopted-ember-addons/ember-file-upload#300]
Affected: latest version

Way to reproduce:
1. Select many files and drag them on the dropzone.
2. Not drop them. Remove them from the dropzone.
3. Try to open the file-browser.
4. See the freeze happens.

The more files you select - the longer freeze you are receiving. 
https://adopted-ember-addons.github.io/ember-file-upload/ - you can reproduce it on the demo with big amount of images (I've tried 180)

ENVIRONMENT:
Ubuntu 18.4
Firefox 72.0.1

Works properly in latest Chrome.

**Comment by Alonski** [comment]
Hmm @fortuneless I am not sure what could be causing this. Have you tried to check the performance tabs while uploading to see what is hanging at?

**Comment by gilest** [comment]
Tested with 394 image files totalling 1.12GB.

Dragging over and back out of the dropzone is a little laggy. Little to no lag opening the file dialog afterwards.

Mac OS X: 10.14.6
Firefox: 73.0.1

I wonder if this is an interaction between Firefox and the Ubuntu file browser.

@fortuneless could you test using [this generic dropzone](https://www.dropzonejs.com)?

**Comment by fortuneless** [comment]
@gilest Yes, I have the same issue only in firefox (chrome and chromium are ok) with the generic dropzone.

**Comment by gilest** [comment]
@fortuneless That's unfortunate, I had a look in the Firefox bug tracker and found a few related issues:

[Dragging files onto file field takes a lot of time to get browser response](https://bugzilla.mozilla.org/show_bug.cgi?id=1530366)
[Delay in drag and drop of files](https://bugzilla.mozilla.org/show_bug.cgi?id=1421858)
[input type=file does not shows file select dialog box](https://bugzilla.mozilla.org/show_bug.cgi?id=1311971)

I suggest you add your own report to these where relevant, or open a new issue with your specific reproduction.

If you find any Firefox performance gains related to the Ember FileUpload implementation please let us know 😄
