### ISSUE TITLE
Firefox Dragging in many files on the dropzone working slow

### ISSUE THREAD

**Issue by fortuneless** [adopted-ember-addons/ember-file-upload#301]
Affected: latest version

Way to reproduce:
1. Select many files and drag them on the dropzone.
2. Release the files.
3. They are not added to the queue.

Note: You need to wait long time until you can release the files (visual confirmation from the dropzone on the demo, for example) to start the upload.

The more files you select - the longer you need to wait. 
https://adopted-ember-addons.github.io/ember-file-upload/ - you can reproduce it on the demo with big amount of images (I've tried 180)

ENVIRONMENT:
Ubuntu 18.4
Firefox 72.0.1

Works properly in latest Chrome.

**Comment by gilest** [comment]
Tested with 394 image files totalling 1.12GB.

Dragging overthe dropzone is laggy. But once dropped the files are immediately visible in the queue and begin uploading.

Mac OS X: 10.14.6
Firefox: 73.0.1

**Comment by fortuneless** [comment]
@gilest Yes, I have the same issue only in firefox (chrome and chromium are ok) with the generic dropzone on ubuntu 18.4.

**Comment by Alonski** [comment]
@fortuneless Could we close this in favor of #300? They seem the same no?

**Comment by fortuneless** [comment]
@Alonski I believe, yes. You are right, It seems that they are the same.
