### ISSUE TITLE
Assertion Failed: Cannot call get with 'dataTransfer' on an undefined object.

### ISSUE THREAD

**Issue by EnotPoloskun** [adopted-ember-addons/ember-file-upload#31]
This issue happens when I have my file browser(in my case - mac os Finder) over drag and drop area(dropzone). 

First upload goes through, but then, if I try to drag second file, this error happens. But if I drag second file out of dropzone and enter it again, upload will work. I found out, that `didEnterDropzone` doesn't happen in this case, which causes fail for this line `set(this[DATA_TRANSFER], 'dataTransfer', evt.dataTransfer);` in `didDrop`. So it means, that initialization of `this[DATA_TRANSFER]` doesn't happen, since `didEnterDropzone` is not triggered, and I have to drag file for second upload out of dropzone and then enter dropzone again. Everything works fine with first file upload.

If I add this line to `DragListener` `drop` function, then everything works fine.

```
      this._listener = null;
```

But I am not sure if it's not breaking something.

**Comment by jelhan** [comment]
Should be fixed by #32 and #63.
