### ISSUE TITLE
Can not switch version in docs app

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#318]
Steps to reproduce:

- Open https://adopted-ember-addons.github.io/ember-file-upload/
- Switch to another version using the select on right top corner.

Expected:

- I see the docs for the selected version.

Actual:

- I see a blank page and a some `404` errors in console.

Switching the version causes a full page refresh. I think that's intended but not sure.

**Comment by gilest** [comment]
This is pretty important. I am looking into it today.

**Comment by gilest** [comment]
Have fixed existing issues in docs builds. Got some ideas about how we can better integrate docs deployments into our pipeline also.

- [ ] Fix docs builds
- [ ] [Jenkins to deploy](https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys) `master` docs after successful test run
- [ ] Release versioned docs when running `release-it` @jelhan is this possible?

**Comment by jelhan** [comment]
Thanks a lot for picking this one up.

>     * [Jenkins to deploy](https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys) `master` docs after successful test run (should automatically deploy `master` and tagged releases)

This should be done TravisCI already: https://github.com/adopted-ember-addons/ember-file-upload/blob/master/.travis.yml#L53-L56

**Comment by gilest** [comment]
> This should be done TravisCI already: https://github.com/adopted-ember-addons/ember-file-upload/blob/master/.travis.yml#L53-L56

Ah – I missed that. A number of versions were missing and the master build was broken.

Will monitor after this PR is merged to make sure it's working properly

**Comment by gilest** [comment]
`master` branch docs build post #321 deployed by Jenkins and looks good 👍
