### ISSUE TITLE
Documentation page is broken on Microsoft Edge

### ISSUE THREAD

**Issue by ndekeister-us** [adopted-ember-addons/ember-file-upload#332]
Hello,

When we try to access documentation page with Microsoft Edge (Version: 18.18362) we have an error

![ember-file-upload-edge](https://user-images.githubusercontent.com/56396753/76638325-8d412c80-654c-11ea-890d-363c0da2c7aa.jpg)

(We have same error with v17 or v16)

Reproduced locally using `ember s` on `master` branch

**Comment by jelhan** [comment]
Thanks for reporting. Seems like Edge is not listed explicitly in the list of target browsers: https://github.com/adopted-ember-addons/ember-file-upload/blob/8fb37d8cbefbd13c8103064a668e15bfc173a0b5/tests/dummy/config/targets.js#L3-L7

Do you have time to test if adding it resolves the issue?

Documentation for JS transpiling and build target configuration could be found [here](https://guides.emberjs.com/release/configuring-ember/build-targets/) and [here](https://cli.emberjs.com/release/advanced-use/asset-compilation/).

**Comment by ndekeister-us** [comment]
Yes, adding `last 1 edge versions` solve it, thanks

Created #333

**Comment by jelhan** [comment]
Fixed by #333 and released as `v3.0.2`.

**Comment by ndekeister-us** [comment]
Just wondering if the documentation page is auto-updating with the last release? (if yes, it is style not accessible via Edge, with the same error)

**Comment by jelhan** [comment]
It's deployed. Latest version is updated accordingly. But can confirm that it's still broken for Edge. Also seeing a syntax error in console. Guess we need to investigate what's going on. Reopening.

**Comment by jelhan** [comment]
Facing a similar issue in one of my apps. Syntax error is thrown in Edge after removing IE11 from build targets. In both cases not transpiled object spread syntax seems to cause the error.

**Comment by jelhan** [comment]
Released v3.0.3, which fixes this issue finally. Docs should be usable in Microsoft Edge again. Please reopen if you still face issues.

**Comment by ndekeister-us** [comment]
Thanks, tested on Edge15-18 and it is ok 🙏
