### ISSUE TITLE
File progress is sometimes NaN

### ISSUE THREAD

**Issue by wagenet** [adopted-ember-addons/ember-file-upload#344]
This appears to happen because total is 0 and you can't divide by 0.

**Comment by jelhan** [comment]
Wondering what the correct value is for `ProgressEvent.total === `0`. Do you know in which case `ProgressEvent.total` is `0`? Is this only happening if the file has zero bytes or could it also happen if the total size is unknown? For the first case the progress should be `100` cause all bytes have been transfered, in the later cases `null` for unknown.

**Comment by wagenet** [comment]
@jelhan looks like this may happen because of Pretender.

**Comment by wagenet** [comment]
I'm using the mirage upload helper which does seem to work correctly, except at the end Pretender sends another progress event using this metric:

```js
progressTotal = body.byteLength || body.size || body.length || 0;
```

However, none of these properties are set by ember-file-upload. It would have to look at `body.file.size`.

**Comment by jelhan** [comment]
Thanks for debugging. So seems we have two issues:

1. Mirage upload handler and pretender are not working together as expected.
2. Ember File Upload does not correctly handle an `ProgressEvent.total` value of `0`.

Both are kind of independent. At least when I get the HTML spec correctly `0` is an allowed value for `ProgressEvent.total`.

I've done some research on the later one. It seems `ProgressEvent.total` is `0` if total size is not computable. It's initalized with `0` and only set in some cases:

> 6.1. Firing events using the ProgressEvent interface
> 
> To fire a progress event named e at target, given transmitted and length, means to fire an event named e at target, using `ProgressEvent`, with the `loaded` attribute initialized to transmitted, and if length is not 0, with the `lengthComputable` attribute initialized to true and the `total` attribute initialized to length. 
>
> https://xhr.spec.whatwg.org/#interface-progressevent

I think it's much more likely that `total` is `0` cause the length is unknown and not cause the file does not have any content. Therefore I think `progress` should be `null` in that case to indicate that it's unknown. Technically it's kind of similar to current `NaN` value in that case but more explicit about that possibility.

It would be a breaking change. But a new major `v4` is already planed. So not a big deal.

**Comment by gilest** [comment]
@wagenet 👋  This is a long shot but if possible could check proposed PR (#475) and attempt to reproduce your issue.
