### ISSUE TITLE
File#queue is undefined

### ISSUE THREAD

**Issue by alexlafroscia** [adopted-ember-addons/ember-file-upload#351]
Upon upgrading to the `v3.0.3`, our test quite is reporting an error from this line

https://github.com/adopted-ember-addons/ember-file-upload/blob/4469a3e36f64167940bac65978b57d1bbd936d1c/addon/file.js#L105

In our instance, `file.queue` is `undefined`, and thus `flush` cannot be called on it.

I have been finding a hard time determining where `File#queue` is defined at all -- it does not seem to be part of the definition of the class.

Is there something we might be missing that's causing this issue? With the previous version -- `2.7.1` -- the tests were working fine. Nothing in the `3.0.0` breaking changes suggests anything we're using has changed.

**Comment by gilest** [comment]
Damn this is probably my fault. Will look into it after work.

**Comment by gilest** [comment]
Is there anything unusual about your usage? Are you adding files to queues by methods other than the public API?

**Comment by jelhan** [comment]
The `queue` property of `File` is set when the file is pushed into a queue: https://github.com/adopted-ember-addons/ember-file-upload/blob/4469a3e36f64167940bac65978b57d1bbd936d1c/addon/queue.js#L50

The property is missed in API docs. This makes it a little bit difficult to find it's origin.

**Comment by alexlafroscia** [comment]
Interesting -- thanks for calling that out @jelhan! Hopefully I can work backwards from there to figure out what's up. 

@gilest there certainly could be 😅 I take it that there's no reason that a `File` would normally not have an associated `queue` if using everything normally? I'm not all that familiar with this library or the code we have that uses it, so there could be something weird in there!

**Comment by alexlafroscia** [comment]
Okay, so it seems like maybe our usage is a bit "different". We _only_ import the `File` class and use that to turn a `Blog` into a `File` to upload

```javascript
  @restartableTask
  upload = function* (html) {
    const blob = new window.Blob([html], { type: 'text/html' });

    const uploadingFile = UploadingFile.create({
      file: File.fromBlob(blob),
      prefix: 'mobile_previews',
      extension: 'html',
      shortLived: true,
    });

    return uploadingFile.upload();
  };
```

I'm going to guess that's not "typical usage". I don't really see anything in the documentation about using the code this way. Should we just drop the addon?

**Comment by alexlafroscia** [comment]
As far as the upload code goes, we're using it inside an Ember Concurrency task

```javascript
  uploadTask: task(function* () {
    const file = this.file;
    const filename = get(file, 'name');

    const signedResponse = yield this.getSignedUrlData(filename);

    yield file.upload(signedResponse.endpoint, { data: signedResponse.fields });
    return signedResponse.url;
  }),
```

Based on the documentation, I _think_ that looks alright?

https://adopted-ember-addons.github.io/ember-file-upload/docs/integration

**Comment by alexlafroscia** [comment]
In our case (as far as I can tell) we manually create the `File` object that is the `this.file` in the snippet above. I don't think the file object ever goes through the components provided by the addon in this case, so we might be bypassing the `Queue` class altogether, where the `queue.push` would add the `queue` prop to the `File`.

**Comment by alexlafroscia** [comment]
If you'd be open to a "fix" for this use-case where we only flush the queue if it's present, I would be happy to put that together. Is there a reason something like that would be dangerous? In our case, I don't believe we're using the file queueing concept at all; at least not in the part of our codebase.

**Comment by jelhan** [comment]
> If you'd be open to a "fix" for this use-case where we only flush the queue if it's present, I would be happy to put that together.

It's currently not that clear what is public API and what not. Maybe it would be better if `File` could only be created through the queue. To not have these edge cases of a `File` that does not belong to any queue.

For now fixing this use case seems to be reasonable. Doesn't make much sense if you need to push the file into a queue for your use case.

But please also add test coverage to avoid a regression. As the public API is not that clear and as we plan some changes to it, having test for all use cases in place is important in my opinion.

**Comment by gilest** [comment]
@alexlafroscia If you could stage a PR for discussion that'd be great.

The change that introduced this was us removing observers in #307.

My assumption when making these changes was that:
-  Files are always created with a queue
- All uploads go through a queue

Since your files weren't in queues before, they wouldn't have triggered the old `flushFilesWhenSettled` observer.

Since #307 queue flushing is explicitly called after for all uploads, and it was assumed that all uploads had a `queue` property.
