### ISSUE TITLE
Camera option not available in Cordova-Android App

### ISSUE THREAD

**Issue by caltabid** [adopted-ember-addons/ember-file-upload#356]
Hi, I would like to use ember-file-upload either to upload a picture or to open the camera to take a picture and upload it directly. The camera option is available in mobile browsers, both with Android-Chrome and iOS-Safari. I'm also using Cordova (via Corber) for Android and iOS apps and this correct behavior is also showing in iOS app but not in Android app. I also tried to use the cordova-plugin-camera and cordova-plugin-media-capture but the camera option is not automatically showing in Android. Any suggestion?

**Comment by jelhan** [comment]
This sounds like a problem with Cordova not with this addon. Did you tested if it's working as expected with a plain `<input>`?
