### ISSUE TITLE
Incorrect documentation for "selectFiles"

### ISSUE THREAD

**Issue by newyork-anthonyng** [adopted-ember-addons/ember-file-upload#359]
In the [documentation for `ember-file-upload/test-support`](https://github.com/adopted-ember-addons/ember-file-upload/blob/d7bc743b35bcea87ac1bfd99feb6369c9bb3d42e/tests/dummy/app/templates/docs/testing.md), the code samples pass a string to `selectFiles`.

But it looks like `selectFiles` only accepts File/Blob objects, not strings.

Let me know if this is correct; I can make a PR for it.
```diff
- await selectFiles('#upload-note', file, 'douglas_coupland.txt');
+ await selectFiles('#upload-note', file); 
```

**Comment by jelhan** [comment]
Good catch. This has changed in last major if I recall correctly. API docs has been updated but not the guides. Would be awesome if you could provide a PR.
