### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by oliverlj** [adopted-ember-addons/ember-file-upload#373]
Is is possible to add typescript definition ?

**Comment by gilest** [comment]
Of course. A PR would be most welcome.

**Comment by jelhan** [comment]
Even porting the addon to TypeScript would be fine for me. Any objections @gilest?

**Comment by gilest** [comment]
No objections here

**Comment by oliverlj** [comment]
I don't know how to add definition to an ember addon.

I did a gist of my types/ember-file-upload directory : https://gist.github.com/oliverlj/fbf9ae7a30f3c221998174291a71a9d6

**Comment by jelhan** [comment]
To be honest I also don't have much experience with TypeScript and ember addons. But this may serve as a good starting point:

- https://ember-cli-typescript.com/docs/ts-guide/with-addons
- https://github.com/typed-ember/ember-cli-typescript/blob/rfc-type-stability/rfcs/0000-type-stability.md

Don't know about the bandwidth of others but I won't have the time to do it in forseable future.

**Comment by chriskrycho** [comment]
I will try to write up a short guide on how to do this next week—something that I post as a comment here but *also* turn into a guide for this on the ember-cli-typescript docs.

**Comment by gilest** [comment]
This would be a very helpful project if you're still interested @oliverlj

**Comment by chriskrycho** [comment]
It’ll be over a year late, but I do plan to write up that guide this coming quarter. Sorry for the delay!

**Comment by oliverlj** [comment]
Hi @chriskrycho , I created PR #545  with types I used on a project but I don't know how to configure ember file upload.

**Comment by gilest** [comment]
Added in #620
