### ISSUE TITLE
Accessibility a11y

### ISSUE THREAD

**Issue by CNovakPB** [adopted-ember-addons/ember-file-upload#387]
Users can't SPACEBAR or ENTER on the `<input type="file">` element, which you've visually hidden and therefore cannot receive focus via TAB.

That means you've prevented any blind or visually impaired user from interacting with this addon. Those users cannot "drag and drop," and need 100% keyboard support.

Developers need to do more to _think about and consider_ the needs of the disabled. Many companies and government entities are required by internal policy or law to provide apps that are accessible to the disabled, based on [W3C standards](https://www.w3.org/standards/webdesign/accessibility) and the Americans with Disabilities Act. Certain entities can open themselves up to lawsuits by ignoring/neglecting a11y in their web applications.

I can work around this shortcoming by querying the DOM and using `.click()` on the input, but this is not ideal.

I encourage all developers on this project to do more in _all their coding efforts to support the needs of the disabled_.

**Comment by NateDawg90** [comment]
Any update on this? Seems important to make these file upload buttons keyboard accessible.

**Comment by jelhan** [comment]
@NateDawg90 Do you have time to work on it?

**Comment by gilest** [comment]
@NateDawg90 it's close!

At the moment I'm considering shipping a modifier that will allow totally standards compliant usage of `<input type="file" />`. Should probably update the #316 issue with my latest design.

**Comment by gilest** [comment]
In v5 we are deprecating the `<FileUpload>` component in favour of a modifier.

See the [Upgrade guide here](https://github.com/adopted-ember-addons/ember-file-upload/blob/master/docs/upgrade-guide.md#fileupload-component).

Feedback would be greatly appreciated – especially on accessibility of the usage example of the new modifier.

**Comment by gilest** [comment]
Should be resolved by v5. Please open new issues for any accessibility concerns.
