### ISSUE TITLE
Implement recipes using ember-concurrency

### ISSUE THREAD

**Issue by tim-evans** [adopted-ember-addons/ember-file-upload#4]
Ember-concurrency is a nice fit for handling concurrent uploads and retries. The API around uploads should nestle in with ember-concurrency to give more advanced users a happy path for multiple uploads and retries.

**Comment by jelhan** [comment]
Personally I'm not a big fan of adding `ember-concurrency` to that many addons. It's a foreseeable update hell as soon as `ember-concurrency` adds a breaking change and addons require different major versions. But we may want to consider this as part of #316.

**Comment by gilest** [comment]
Is the suggestion to bundle `ember-concurrency` with the addon?

I thought it meant the API should fit nicely with `ember-concurrency`.

@tim-evans ?

**Comment by gilest** [comment]
Looking at this again I believe the suggestion was that we use `ember-concurrency` in the docs examples rather than bundling it with the addon.

I generally agree and updated all the examples to use concurrency tasks in #522
