### ISSUE TITLE
"ember-file-upload/test-support" `selectFiles` test-support crashing on Ember 3.20.1

### ISSUE THREAD

**Issue by fdrobidoux** [adopted-ember-addons/ember-file-upload#424]
I'm working on tests for a project at work, and I have to test events following the @onFileAdd action.

So I used `selectFiles` to simulate an upload, and in the ran test, I get this in the console :

```
You attempted to schedule an action in a queue (actions) for a method that doesn't exist
    at DeferredActionQueues.schedule (backburner.js:389)
    at Backburner._scheduleExpiredTimers (backburner.js:1122)
    at Backburner._runExpiredTimers (backburner.js:1095)
```

This doesn't fail any tests, but it does shut down the whole testing suite, which means the last remaning test after that one does not run.

Here's my test case :

```js
test('it calls the assigned onFileAdd action when uploading.', async function (assert) {
  assert.expect(1);

  const data = new Uint8Array([
    137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,8,0,0,
    0,8,8,2,0,0,0,75,109,41,220,0,0,0,34,73,68,65,84,8,215,99,120,
    173,168,135,21,49,0,241,255,15,90,104,8,33,129,83,7,97,163,136,
    214,129,93,2,43,2,0,181,31,90,179,225,252,176,37,0,0,0,0,73,69,
    78,68,174,66,96,130
  ]);
  let file = new File(data, 'smile.png', { type: 'image/png' });

  this.set('onFileAddAction', async function() {
    await timeout(100);
    assert.ok();
    return file;
  });
  await render(hbs`<FileUploaded @evidenceList={{evidences}} @readOnly={{false}} @onFileAdd={{onFileAddAction}}/>`);

  await selectFiles('.file-upload input', file);
});
```

Any ideas what's the problem? I'm using the latest version of ember-file-upload, and using Ember 3.20.1.

Thanks!

**Comment by jelhan** [comment]
Sounds strange. Are you able to setup a reproduction? Ember Twiddle, CodeSandox or GitHub repo would be great. Even better: A merge request with a failing test.

**Comment by fdrobidoux** [comment]
So i'm doing what you told me to do and tried to run the tests on my end. And I'm getting this even less useful error :

```
"Error: Assertion Failed: Config object passed to computed can only contain `get` and `set` keys.
    at new EmberError (http://localhost:7357/assets/vendor.js:3940:31)
    at assert (http://localhost:7357/assets/vendor.js:2804:23)
    at new ComputedProperty (http://localhost:7357/assets/vendor.js:31486:42)
    at computed (http://localhost:7357/assets/vendor.js:31804:18)
    at http://localhost:7357/assets/vendor.js:65922:412
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (http://localhost:7357/assets/vendor.js:65922:369)
    at Module.callback (http://localhost:7357/assets/vendor.js:67044:7)
    at Module.exports (http://localhost:7357/assets/vendor.js:111:32)
    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)"
```

I'm starting to think my workstation settings are the problem lol.

**Comment by jelhan** [comment]
That's strange. I assume you haven't done any changes before seeing the tests failing? Did you followed the [contributing docs](https://github.com/adopted-ember-addons/ember-file-upload/blob/master/CONTRIBUTING.md) by word? Did you verified that your node version is supported? The CI is passing. I also verified locally that tests are running fine for latest `master` branch.

**Comment by fdrobidoux** [comment]
I don't remember how, but I think I eventually figured it out. Sorry if you come here from google, I can't share code from my workplace. 🤐
