### ISSUE TITLE
S3 Uploads without FormData

### ISSUE THREAD

**Issue by datajohnny** [adopted-ember-addons/ember-file-upload#43]
I have a question how can I just so a single image upload without having a formdata wrapper.

**Comment by ryanjavens** [comment]
@datajohnny do you have a code example to help your question?  I'd love to take a look and try to help you out!

**Comment by datajohnny** [comment]
@ryanjavens Hi I was wondering if it was possible to just do the image itself like

```javascript
let $form = $('#file_upload');
let file = $form.files[0];
$.ajax(url, file, 'PUT');
```

**Comment by donaldwasserman** [comment]
@datajohnny if you're still having some problems with that and s3, i think the problem is more on S3's side, which requires a bunch of different form data.
