### ISSUE TITLE
Assert change on dragEnter in acceptance test

### ISSUE THREAD

**Issue by thiberaw** [adopted-ember-addons/ember-file-upload#438]
With this as template in the application

```hbs
<FileDropzone class='dropzone' @name='document' as |dropzone queue|>
    <div>
        {{#if queue.files.length}}
            'Loading...'
        {{else}}
            <FileUpload
              @name='document'
              @accept='.doc,application/pdf'
              @onfileadd={{action 'onSubmit'}}
            >
              'Drag and drop file or browse'
            </FileUpload>
            <p data-test-error={{stringify (not dropzone.valid)}}>
              'Word or PDF files only'
            </p>
        {{/if}}
    </div>
</FileDropzone>
```

and then in the acceptance test file

```js
const data = new Uint8Array([
    137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,8,0,0,
    0,8,8,2,0,0,0,75,109,41,220,0,0,0,34,73,68,65,84,8,215,99,120,
    173,168,135,21,49,0,241,255,15,90,104,8,33,129,83,7,97,163,136,
    214,129,93,2,43,2,0,181,31,90,179,225,252,176,37,0,0,0,0,73,69,
    78,68,174,66,96,130
]);
let file = new File(data, 'smile.png', { type: 'image/png' });
await dragEnter('.dropzone', file);
assert.dom('[data-test-error="true"]').exists();
```

it fails because the `data-test-error` value is still `false`

Is there something that shall be done or wait for in order to have the attribute's value updated by the `dropzone.valid` ?  
It only fails in the acceptance test, testing it manually works fine.

**Comment by gilest** [comment]
Hi @thiberaw thanks for reporting 👍 

I tested this by creating an integration test:

```js
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import hbs from 'htmlbars-inline-precompile';
import { dragEnter } from 'ember-file-upload/test-support';

module('Integration | dropzone.valid change on dragenter', function(hooks) {
  setupRenderingTest(hooks);

  test('addon user', async function(assert) {
    await render(hbs`
    <FileDropzone class="dropzone" @name="document" as |dropzone queue|>
      <div>
        {{#if queue.files.length}}
          "Loading..."
        {{else}}
          <FileUpload
            @name="document"
            @accept=".doc,application/pdf"
            @onfileadd={{noop}}
          >
            "Drag and drop file or browse"
          </FileUpload>
          <p data-test-error={{if (not dropzone.valid) "true" "false"}}>
            "Word or PDF files only"
            isValid: {{dropzone.valid}}
          </p>
        {{/if}}
      </div>
    </FileDropzone>
    `);

    const data = new Uint8Array([
      137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,8,0,0,
      0,8,8,2,0,0,0,75,109,41,220,0,0,0,34,73,68,65,84,8,215,99,120,
      173,168,135,21,49,0,241,255,15,90,104,8,33,129,83,7,97,163,136,
      214,129,93,2,43,2,0,181,31,90,179,225,252,176,37,0,0,0,0,73,69,
      78,68,174,66,96,130
    ]);
    let file = new File(data, 'smile.png', { type: 'image/png' });
    await dragEnter('.dropzone', file);
    assert.dom('[data-test-error="true"]').exists();
  });
});
```

This test successfully passes ✅ 

Note that we don't have a `stringify` helper so I used the `if` helper in-line...

```hbs
<p data-test-error={{if (not dropzone.valid) "true" "false"}}>
```

You may need to check your `stringify` helper and ensure it is returning "true" as a string object.

In my testing if the data attribute is assigned a boolean your dom selector will not be matched. For example:

Input:

```hbs
<p data-test-error={{true}}></p>
```

Output:

```html
<p data-test-error></p>
```

Let me know if this helps.

**Comment by thiberaw** [comment]
Thank you @gilest  
I'll follow your steps and let you know.

**Comment by thiberaw** [comment]
So, I just figured out what was happening.  
First i didn't want to do an integration test like this one, because obviously it was just test the `dropzone.valid` and I guess you already do this pretty well :smile: and i wanted an acceptance test because I needed to run it with mirage.

  
But still I wanted to test it, and it failed.  
The reason is (and I am sorry for not mentioning it) because i was `dragEnter`ing more files before the image all with accepted extensions.

1.  `dragEnter` accepted
2.  `dragEnter` not accepted
3.  `dragEnter` accepted

So, and thanks to this second try, I thought that I may need to `dragLeave` between each step, and it works.

**Comment by thiberaw** [comment]
Thanks again @gilest 

I my opinion you can close this ticket as this is not a bug, but rather a misunderstanding of what needs to be done when writing tests using the addon.

**Comment by thiberaw** [comment]
And by the way, you were right to point out the `stringify` ...

**Comment by gilest** [comment]
Thanks for reporting back :)
