### ISSUE TITLE
Preview File

### ISSUE THREAD

**Issue by shasiuk1** [adopted-ember-addons/ember-file-upload#45]
Is there a way to add preview of file (image) and to show progress for each one?

**Comment by tim-evans** [comment]
Yes there is!

You can call `readAsDataURL` to get a preview url of the file and you can observe `file.progress` to update a loading bar:

```hbs
{{file-upload name='photos' onfileadd=(action 'upload')}}
{{#each (file-queue 'photos') as |file|}}
  <img src={{file.url}} alt={{file.name}} />
  {{progress-bar progress=file.progress}}
{{/each}}
```

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    upload(file) {
      file.readAsDataURL().then(function (url) {
        file.set('url', url);
      });

      // Upload here
    }
  }
});
```

**Comment by checkerap** [comment]
I might be mistaken, but shouldn't the iterator be like this:

```
{{#with (file-queue name="photos") as |queue|}}
	{{#each queue.files as |file|}}
		<img src={{file.url}} alt={{file.name}} />
	{{/each}}
{{/with}}
```

That is what I found in the helper source code. Your example code {{#each ... doesn't work for me.

**Comment by tim-evans** [comment]
😅  yeah, that looks right

**Comment by tim-evans** [comment]
Thanks @checkerap; I fixed the snippet

**Comment by gilest** [comment]
@Alonski I think this can be closed.
