### ISSUE TITLE
Is ember-route-action-helper really necessary in the integration docs

### ISSUE THREAD

**Issue by bartocc** [adopted-ember-addons/ember-file-upload#50]
I think the docs could be updated to better help someone starting with the addon.

If you copy/paste the snippets from the readme, you'll miss ember-concurrency and ember-route-action-helper if you don't already have them in your project.

I'll address ember-concurrency in another issue.

As for ember-route-action-helper, do we really need to have a route action for the upload to work? If not, why not move the action from the route to a controller or component? That would remove one possible dependency error when copy/pasting the example code.

**Comment by tim-evans** [comment]
We don't, and yes, it would be good for this to work without that ember-route-action-helper. I'm not sure how much controllers are recommended for ember apps..

**Comment by angelomachado** [comment]
In my opinion there is no problem using controllers. When the day comes there will be an upgrade path.

**Comment by tim-evans** [comment]
https://github.com/tim-evans/ember-file-upload/issues/122

**Comment by gilest** [comment]
The `route-action` helper was removed from the docs in #281 .
