### ISSUE TITLE
[v5] Queue not immediately filled when uploading multiple files

### ISSUE THREAD

**Issue by nickschot** [adopted-ember-addons/ember-file-upload#697]
In v4 when you upload multiple files at once, the `file.queue` that is present in the `onFileAdd` `<FileUpload/>` argument call will immediately on the first `onFileAdd` call have all of the files that were uploaded. In v5 this is no longer the case and the first call will just have the first file etc.

Not sure if this is an on purpose change or a regression, hence the issue report. Either way it seems to be a side effect of the new listener system that was implemented.

**Comment by nickschot** [comment]
Thanks for that! I'll be back to the codebase where I found this in 2 weeks to confirm. Will report back & investigate if we can migrate the code to the newer approach.

**Comment by gilest** [comment]
Fix released in 5.0.0-beta.7

**Comment by nickschot** [comment]
Appears to work, thanks again!
