### ISSUE TITLE
Blueprints don't install test-support/helpers/upload.js into the project

### ISSUE THREAD

**Issue by psbanka** [adopted-ember-addons/ember-file-upload#70]
The documentation for the acceptance-test helpers indicates that you should be able to import `upload` from `../../helpers/upload`, but that file is not installed. I don't know if it was intended that this be installed via a blueprint or not? 

doing this manually with `cp node_modules/ember-file-upload/test-support/helpers/upload.js tests/helpers/` seemed to do the trick, however.

**Comment by tim-evans** [comment]
Oh, that's some weird thing that Ember does, merging the test helper in test mode. Lemme get some docs for you :)

**Comment by tim-evans** [comment]
For some info, see here: https://williamsbdev.com/posts/Ember-CLI-test-support/

`test-support` should be merged in by ember-cli. Something may have changed in the most recent of ember. :/

**Comment by tim-evans** [comment]
Thanks for the report

**Comment by jelhan** [comment]
Outdated. It's exported from 'ember-file-upload/test-support' since quite some time.
