### ISSUE TITLE
Max file limit handling in v5

### ISSUE THREAD

**Issue by mkszepp** [adopted-ember-addons/ember-file-upload#712]
I want to know, if there is planned a option for max file limit in `v5` (for example allow max 3 files to upload)

I know, that html out of the box doesn't support this yet, but there is possible to handle with listener `drop` (for drag'n/drop) and `onChange` on input field.

My plan was to use the callbacks `onDrop` / `onFilesSelected` to handle this, but after code check, i have seen, that this callbacks will be called after the queue insert, For this reason this callbacks are coming to late for me. This callbacks has also confused me a little bit :), because the callbacks are not after dropping / file selected, they are more `afterFilesAdded`. A callback like `onDrop` / `onFilesSelected` is for me before adding files in the queue or?

After this discovery i was going on to check if there is already a other callback, which i can use for my limitation and i have seen the `filter` callback, but in this callback i have the problem that there is missing the index + all files, and so there is also here not possbile to make a file limiation, before adding in queue.
I think, the solution would be, to add the index & all files as parameter in `filter`.
If this solution is ok, i can also help to extend this callbacks.

https://github.com/adopted-ember-addons/ember-file-upload/blob/8add316307645fc738acbcf502d4f05ca6e5df65/ember-file-upload/addon/components/file-dropzone.ts#L302-L322

https://github.com/adopted-ember-addons/ember-file-upload/blob/4a329e9b1c01e46a65b12b2b3691aae473cc58ce/ember-file-upload/addon/queue.ts#L208-L229

**Comment by gilest** [comment]
Hey – thanks for reporting.

Would something like the following work?

```js
const MAX_FILES = 3;

export default class ExampleComponent extends Component {
  @service fileQueue;

  get queue() {
    return this.fileQueue.findOrCreate('your-queue-name');
  }

  @action
  enforceMaxFiles() {
    return this.queue.files.length < MAX_FILES;
  }
}
```

Obviously passing `this.enforceMaxFiles` as your `filter` callback.

Although this is limiting the files that can be uploading at any given time, rather than limiting the number of files that can be selected each drop/select.

> I think, the solution would be, to add the index & all files as parameter in filter.

This is a reasonable solution, anyway, and a non-breaking change.

**Comment by mkszepp** [comment]
Hi @gilest,
thank for your answer.

Yes, this solution works, when i want add files until the limit is reached, but is there also a possiblity to block all selected images, when someone selects 4 images, but only 3 are allowed?
In this case i want to inform the user directly with a alert for example `Sorry, you have selected more images than allowed. No files were added` and skip all selected files.

**Comment by gilest** [comment]
> I think, the solution would be, to add the index & all files as parameter in filter.

Want to make a PR with your solution?

Suggested filter method signature: `file, files, index`.
