### ISSUE TITLE
Repeated, rapid didLeaveDropzone and didEnterDropzone results in race condition

### ISSUE THREAD

**Issue by blarosen95** [adopted-ember-addons/ember-file-upload#715]
The potential for a reproducible race condition exists where the value of `file-dropzone`'s `dataTransfer` can remain as `null` from `didLeaveDropzone` when `didDrop` is called. This will result in Ember failing to set the object's wrapped property and failing to assert that the object is not yet destroyed.
 
https://github.com/adopted-ember-addons/ember-file-upload/blob/97925ebfd66a062a71c1bf0f7670bfeccc36bf29/addon/components/file-dropzone/component.js#L275

The issue appears to be resolved by something as simple as starting the `didDrop` function with:
```
if ([undefined, null].includes(this[DATA_TRANSFER])) {
      return;
    }
```

Alternatively, there is similar logic present in https://github.com/adopted-ember-addons/ember-file-upload/blame/6b1f5ee17d0bc6a04ebd3a2edb138768e18d4ee7/ember-file-upload/addon/components/file-dropzone.ts#L218 which would also fix this issue.

Edited to add request: Could the conditions present in the linked commit be brought in during V4?

**Comment by gilest** [comment]
> Edited to add request: Could the conditions present in the linked commit be brought in during V4?

Can you not try this in a v5 beta?

I think it may have been solved by conditional gating upstream.

**Comment by blarosen95** [comment]
> > Edited to add request: Could the conditions present in the linked commit be brought in during V4?
> 
> Can you not try this in a v5 beta?
> 
> I think it may have been solved by conditional gating upstream.

I'm not sure that I understand. While the conditional gating is present in master, it doesn't appear to be on a tagged release, it looks like it was only added in the last few commits.

**Comment by gilest** [comment]
Ah you're right. I haven't been able to cut a release since we migrated to monorepo. Will need to find time to resolve. In the meantime can you try:

```json
    "ember-file-upload": "adopted-ember-addons/ember-file-upload#13ffe87bd56d67988050f5883a50446555d3ebe5",
```

**Comment by gilest** [comment]
> Yes, it does seem related to #201 The flickering is one of the first steps in my current repro; but the null race condition does persist with the `pointer-events: none` mentioned in that issue.

I see, thanks for checking.

> I've attempted to bring in the package at the commit you mentioned (alongside specifying the workspace), but there's now build errors during `ember serve`:
```ember-file-upload/components/file-upload.ts: `this.queue.selectFile` is not a valid name for a modifier on line 16.```

What version of ember are you running? I think that the local modifier feature is only available in 3.25+.

**Comment by blarosen95** [comment]
Awesome, I was running on ember 3.24.5 but ember-file-upload works after upgrading to 3.25.4. Can no longer reproduce the original issue. There's some new stuff to work out but I've a feeling it's part of our implementation and not the addon as it seems to be related to how we're using the file queue on our end. Thank you!

**Comment by gilest** [comment]
> I haven't been able to cut a release since we migrated to monorepo.

FYI @blarosen95 I managed to release `5.0.0-beta.8`

**Comment by blarosen95** [comment]
> > I haven't been able to cut a release since we migrated to monorepo.
> 
> FYI @blarosen95 I managed to release `5.0.0-beta.8`. You can switch to using that from the commit ref I gave you earlier.
> 

Awesome, thank you! I've gotten everything squared away off of that ref commit and the error is no longer reproducible. Will switch it over to the release when I get the chance.
