### ISSUE TITLE
FileDropzone doesn't work with extensions

### ISSUE THREAD

**Issue by AddisonG** [adopted-ember-addons/ember-file-upload#753]
I copied a default example [from the docs](https://adopted-ember-addons.github.io/ember-file-upload/docs/api/components/file-dropzone).
I changed a single line, from `@accept="image/*"` to `@accept=".png"`.

```hbs
<FileDropzone @name="photos" as |dropzone queue|>
  {{#if dropzone.active}}
    {{#if dropzone.valid}}
      Drop to upload
    {{else}}
      Invalid
    {{/if}}
  {{else if queue.files.length}}
    Uploading {{queue.files.length}} files. ({{queue.progress}}%)
  {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if dropzone.supported}}
        Drag and drop images onto this area to upload them or
      {{/if}}
      <FileUpload @name="photos"
                  @accept=".png"       {{!-- THIS IS THE LINE I CHANGED --}}
                  @multiple=true
                  @onFileAdd={{this.uploadImage}}>
        <a id="upload-image" tabindex=0>Add an Image.</a>
      </FileUpload>
    </p>
  {{/if}}
</FileDropzone>
```

This causes the drag-and-drop functionality to break, and claim that every single file is invalid, in both the latest Chrome and Firefox.

The click-to-upload functionality works correctly, and asks for the correct file type (.png).

---

Is this an issue?
Is there a workaround?

Should the [docs for @accept](https://adopted-ember-addons.github.io/ember-file-upload/docs/api/components/file-dropzone#accept) be updated to say that this does not work?

```
accept: string
A list of MIME types / extensions to be accepted by the input
```

^ This is wrong. It does not fully support extensions.

**Comment by gilest** [comment]
Hi @AddisonG 👋🏻  and thanks for reporting.

You're right – `@accept/accept` validation is inconsistent.

That's why we decided to remove it in `v5`.

I suggest you upgrade to the latest `5.0.0-beta.10` if you can and check the new docs regarding [Custom Validation](https://ember-file-upload.pages.dev/docs/file-validation#custom-validation).

**Comment by AddisonG** [comment]
Thanks gilest

I'd love to move to v5, but unfortunately we're stuck on an older version of Ember, for now.

I see that the rest of the internet actually suffers from this problem as well, so it's not just this package. I'll write some code which checks it after the file is dragged on, which appears to be the standard procedure. If imgur can't check file extension, then I sure as heck don't need to.

Also, the actual extension I want is a strange, custom extension for our products, which doesn't actually have a mime type (Something like `.asdf`).

Thanks for the help.

**Comment by gilest** [comment]
Right – good luck!

For context this has been raised a few times. Maybe reading some of these is helpful:
#520 
#232
#127
#376

You can see why we eventually dropped internal validation in #578 

Let me know if you need help with anything else
