### ISSUE TITLE
TypeError: `dataTransfer.getData` is not a function

### ISSUE THREAD

**Issue by nwhittaker** [adopted-ember-addons/ember-file-upload#768]
Seeing an issue with this block when testing a component that makes use of more than one drag-and-drop addon:

https://github.com/adopted-ember-addons/ember-file-upload/blob/8d0a8dcac30e96abe02e027ba8682685b8f38ef7/ember-file-upload/addon/system/data-transfer-wrapper.ts#L22-L38

---
For better or worse, I have an implementation where a file can be dropped on top of a table of items whose rows can be reordered via drag-and-drop. The test helper for the row-level drag-and-drop mocks a `DataTransfer` object that includes a `getData()` implementation. When this mocked-event object is dispatched, it hits the file-upload drop handler first. This causes an entry in `getDataSupport`:

https://github.com/adopted-ember-addons/ember-file-upload/blob/8d0a8dcac30e96abe02e027ba8682685b8f38ef7/ember-file-upload/addon/system/data-transfer-wrapper.ts#L27

Later, when the `ember-file-upload` test helper is used to drop a file, it mocks a `DataTransfer` object that does not include a `getData()` implementation:

https://github.com/adopted-ember-addons/ember-file-upload/blob/8d0a8dcac30e96abe02e027ba8682685b8f38ef7/ember-file-upload/addon-test-support/index.ts#L80

Normally, this would throw and get caught:

https://github.com/adopted-ember-addons/ember-file-upload/blob/8d0a8dcac30e96abe02e027ba8682685b8f38ef7/ember-file-upload/addon/system/data-transfer-wrapper.ts#L32

But since the first drag event added an entry to `getDataSupport`, the `null` check above fails and execution ends up here where `getData()` is not defined:

https://github.com/adopted-ember-addons/ember-file-upload/blob/8d0a8dcac30e96abe02e027ba8682685b8f38ef7/ember-file-upload/addon/system/data-transfer-wrapper.ts#L37

**Comment by gilest** [comment]
Not sure it's always possible but ideally the other addon's events would never reach this addon's event handlers.

I wonder if fixing #446 might go a way towards solving this since it would limit the events bound to FileDropzone it its own element.

What is the other addon you're using by the way? Would like to see how it constructs events etc.

**Comment by nwhittaker** [comment]
>Not sure it's always possible but ideally the other addon's events would never reach this addon's event handlers.

I was writing a test for when a row was dropped outside of the table but still within the file drop zone -- so didn't hit the normal `drop` handler first. I see I can work around the problem by adding my own handlers to the file drop zone that filters out the the unsupported drag events. Not sure how to write the filter w/out making it aware of the mocked data-transfer interface, though.

>I wonder if fixing https://github.com/adopted-ember-addons/ember-file-upload/issues/446 might go a way towards solving this since it would limit the events that FileDropzone listens to.

In my case, the table is embedded inside the file-dropzone component, so I suspect not.

Thinking of a solution, I'm wondering if it can start w/ just further fleshing out the mocked data-transfer object, and go from there...

>What is the other addon you're using by the way? Would like to see how it constructs events etc.

I'm using the test helpers from the [`ember-drag-drop` addon][1]. Here's the [mock drag event][2] it creates with a mocked data transfer object.

[1]: https://github.com/mharris717/ember-drag-drop
[2]: https://github.com/mharris717/ember-drag-drop/blob/master/addon-test-support/helpers/mock-event.js

**Comment by gilest** [comment]
Hey @nwhittaker . I started writing a regression test for this today – but it kept passing!

That's because all features calling `getData` have been disabled since `v5.0.0`. Hopefully you can upgrade and avoid this problem altogether.

If/when we do reintroduce the `getData` usage I'll make sure it's more robust.
