### ISSUE TITLE
file-upload component is missing in v6

### ISSUE THREAD

**Issue by bracke** [adopted-ember-addons/ember-file-upload#784]
I'm getting an error when building with v6. Works fine with previous version.
This is using embroider & webpack & node 14.

Looks like the component file-upload is missing.

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../node_modules/ember-file-upload/components/file-upload' in '$TMPDIR/embroider/9ee008/components/file-upload.js'
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/bent/Projekter/FormPlus/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/bent/Projekter/FormPlus/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:975:5
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve '../node_modules/ember-file-upload/components/file-upload' in '$TMPDIR/embroider/9ee008/components/file-upload.js'
  - errorMessage: components/file-upload.js: Module not found: Error: Can't resolve '../node_modules/ember-file-upload/components/file-upload' in '$TMPDIR/embroider/9ee008/components/file-upload.js'
        at PackagerRunner (@embroider/webpack)

**Comment by gilest** [comment]
Yes it was deprecated in v5 and removed in v6. See the [Upgrading to v5 guide](https://ember-file-upload.pages.dev/docs/upgrade-guide)

**Comment by gilest** [comment]
Apologies – I forgot to remove the public export. Patch incoming.

**Comment by gilest** [comment]
Released 6.0.1 which should fix this. Please let me know if you encounter anything else
