### ISSUE TITLE
file-upload not found in v6.0.1

### ISSUE THREAD

**Issue by bracke** [adopted-ember-addons/ember-file-upload#786]
I'm getting an error when using 6.1. 
Version 5 worked without error.

This is with embroider & webpack & node 14.

The component "components/help/manual-form.hbs" is the component that uses ember-file-upload and contains the tag <FileUpload ...>  
 
 - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../file-upload.js' in '$TMPDIR/embroider/9ee008/components/help/manual-form.hbs'
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/bent/Projekter/FormPlus/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/bent/Projekter/FormPlus/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/bent/Projekter/FormPlus/node_modules/webpack/lib/NormalModuleFactory.js:975:5
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve '../file-upload.js' in '$TMPDIR/embroider/9ee008/components/help/manual-form.hbs'
  - errorMessage: components/help/manual-form.hbs: Module not found: Error: Can't resolve '../file-upload.js' in '$TMPDIR/embroider/9ee008/components/help/manual-form.hbs'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error

**Comment by gilest** [comment]
The `<FileUpload>` component was deprecated in v5 and removed in v6. See the [Upgrading to v5 guide](https://ember-file-upload.pages.dev/docs/upgrade-guide)

**Comment by bracke** [comment]
Ah, I missed that. 
Can confirm it works. 

Thanks for the very fast response 👍
