### ISSUE TITLE
Error: Can't resolve 'miragejs' in v7.0.1

### ISSUE THREAD

**Issue by mkszepp** [adopted-ember-addons/ember-file-upload#816]
Ember JS: v4.4.0
Ember file upload: v7.0.1

We are getting the following error with the latest 7.x version (7.0.1):

Module not found: Error: Can't resolve 'miragejs' in '$TMPDIR/embroider/f945b2/node_modules/ember-file-upload/dist/index.js'

https://github.com/adopted-ember-addons/ember-file-upload/blob/3b1188dfe3b60f5538f7132bd8b9c087fddb8c5c/ember-file-upload/src/mirage/upload-handler.ts#L2

In package.json there is defined mirage as optional.

Adding manual the miragejs as dependency solves the problem.

**Comment by gilest** [comment]
Hey @mkszepp thank you for reporting. This was due to an oversight I made during the recent upgrade – sorry about that. Should be fixed in 7.0.2.

**Comment by mkszepp** [comment]
@gilest thanks for this fast fix 🚀🚀
