### ISSUE TITLE
Missing type definitions for the FileQueue service

### ISSUE THREAD

**Issue by mayatron** [adopted-ember-addons/ember-file-upload#826]
The `FileQueue` service type definitions should be exported I believe. Currently they don't appear to be:

https://github.com/adopted-ember-addons/ember-file-upload/blob/a1686cd74bcb59e9e950ab2a363ef3130f986071/ember-file-upload/src/index.ts#L7-L18

Am I missing something here? Or can we include this service in the exported types?

**Comment by gilest** [comment]
Hey @mayatron 👋🏻 thanks for reporting. Should be fixed in [7.0.3](https://github.com/adopted-ember-addons/ember-file-upload/releases/tag/v7.0.3). Let me know if it isn't
