### ISSUE TITLE
Update `selectFile` casing

### ISSUE THREAD

**Issue by patrickberkeley** [adopted-ember-addons/ember-file-upload#863]
Currently the `queue.selectFile` errors with the default ember-template-lint rules: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/modifier-name-case.md

This ticket is a request to change the casing from `selectFile` to `select-file`.

**Comment by jelhan** [comment]
This seems to a bug in the Ember template lint rule to me.

Dasherized properties look wrong to me:

```hbs
<input type="file" {{queue.select-file}}>
```

Having camelCase property and method names is a well established convention in JavaScript ecosystem. I don't feel there is much benefit in having an exception for methods, which are meant to be used as modifiers.

I understand the intention of the rule. It makes sense for global modifiers. Especially as in that case both cases are working. But the rule should not be applied to variables in local scope in my opinion.

Are you sure that this rule is enabled by default? Accordingly to docs it should be only enabled if users opt-in to stylistic rule set.

**Comment by patrickberkeley** [comment]
@jelhan thanks for the response. Using camelCase for methods for consistency makes sense.

You are correct, we have `stylistic` rules enabled.

**Comment by gilest** [comment]
Thanks @patrickberkeley @jelhan. When naming this modifier I searched for examples of local modifiers in the community and found they were using this format.

As this is a new area in ember and there aren't many official docs detailing local modifiers yet. If the community arrives upon a different standard I'd be open to renaming this property as a breaking change.
