### ISSUE TITLE
Add interfaces folder to addon.publicEntrypoints

### ISSUE THREAD

**Issue by BoussonKarel** [adopted-ember-addons/ember-file-upload#891]
In our app, we use TypeScript and import the QueueName interface from 'ember-file-upload/interfaces'

Because it is not added to publicEntrypoints of the V2 addon, the file we import changes to 'ember-file-upload/interfaces-fc8a799a'

[See PR](https://github.com/adopted-ember-addons/ember-file-upload/pull/890)

**Comment by gilest** [comment]
We're not going to expose all interfaces but instead export `QueueName` specifically in #897
